Autoupdate of 4 submodules
*common updated to 0f0c60834384df16242a6fa89201d849e0c80b97
Merge 69352bd52b26 ("Merge tag 'mfd-next-6.16' of git://git.kernel.org/pub/scm/linux/kernel/git/lee/mfd") into android-mainline

Steps on the way to v6.16-rc1

Change-Id: I4f31bf92329eaeb7c81c6ac3c1db35bcd6645e5c
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/power/mitigation updated to 66a6879082946b96cc9828fa25311a8841869ba1
bcl: rename s2mpg10.h -> s2mpg10-local.h

The core s2mpg10 driver was upstreamed in commit 5338709089b7 ("mfd:
sec: Add support for S2MPG10 PMIC"), see [1]. This causes several name
collisions with the downstream version since it shares the same header
file 's2mpg10.h', e.g.:

  include/linux/mfd/samsung/s2mpg10-register.h:20:2: error: redefinition of enumerator 'S2MPG10_COMMON_CHIPID'
   20 |         S2MPG10_COMMON_CHIPID = 0x0,
      |         ^

To resolve these build issues, rename the downstream header to
's2mpg10-local.h'. This serves as a temporary workaround while the
codebase switches to use the upstream version of the driver.

Bug: 429859675
Cc: André Draszik <draszik@google.com>
Link: https://git.kernel.org/torvalds/c/5338709089b7 [1]
Change-Id: Ibd69dafaa72e48be2d376aa59590fe956ccabd2c
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/power/reset updated to 05061a5092966d6e9c8dba22c9718de1f4716ffe
power: reset: rename s2mpg10.h -> s2mpg10-local.h

The core s2mpg10 driver was upstreamed in commit 5338709089b7 ("mfd:
sec: Add support for S2MPG10 PMIC"), see [1]. This causes several name
collisions with the downstream version since it shares the same header
file 's2mpg10.h', e.g.:

  include/linux/mfd/samsung/s2mpg10-register.h:20:2: error: redefinition of enumerator 'S2MPG10_COMMON_CHIPID'
   20 |         S2MPG10_COMMON_CHIPID = 0x0,
      |         ^

To resolve these build issues, rename the downstream header to
's2mpg10-local.h'. This serves as a temporary workaround while the
codebase switches to use the upstream version of the driver.

Bug: 429859675
Cc: André Draszik <draszik@google.com>
Link: https://git.kernel.org/torvalds/c/5338709089b7 [1]
Change-Id: I5b8900f765552a97b13357153470f7847a743c51
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/soc/gs updated to 000e8bed72b45efdc0121291ff1c13327945753c
treewide: rename s2mpg10.h -> s2mpg10-local.h

The core s2mpg10 driver was upstreamed in commit 5338709089b7 ("mfd:
sec: Add support for S2MPG10 PMIC"), see [1]. This causes several name
collisions with the downstream version since it shares the same header
file 's2mpg10.h', e.g.:

  include/linux/mfd/samsung/s2mpg10-register.h:20:2: error: redefinition of enumerator 'S2MPG10_COMMON_CHIPID'
   20 |         S2MPG10_COMMON_CHIPID = 0x0,
      |         ^

To resolve these build issues, rename the downstream header to
's2mpg10-local.h'. This serves as a temporary workaround while the
codebase switches to use the upstream version of the driver.

Bug: 429859675
Cc: André Draszik <draszik@google.com>
Link: https://git.kernel.org/torvalds/c/5338709089b7 [1]
Change-Id: I7382135b08ae72f44d6c66b3d209290ce97424fb
Signed-off-by: Carlos Llamas <cmllamas@google.com>