Autoupdate of 2 submodules
*build updated to ca83bf807fb2aeb9f4561dca31e04e801ab4d84c
kleaf: cc_testing: disable glibc fully_static_link test

This test is causing linker issues after upgrading to clang-r522817. Lets
disable it temporarily while we continue to investigate the problem.

  ld.lld: error: duplicate symbol: __lll_lock_wait_private
  ld.lld: error: duplicate symbol: __lll_unlock_wake_private

Bug: 348087663
Change-Id: I23d5dd5e6faf52c82ed002d8d0e28df3a86a9d66
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*common updated to 12700c0d8ccfa498f3ea377f92e870df00edb8ef
ANDROID: fix the --entry linker flag for kselftest

Use the correct way to pass linker flags. This fixes the build error
in kselftests after upgrading to clang-r522817:

  clang: error: unknown argument: '-ereal_start'

Suggested-by: Matthias Maennich <maennich@google.com>
Fixes: bb9d33b2a707 ("ANDROID: Add x86 specific self tests")
Change-Id: Ibbb61d62a4781f5be95faf655c3ad14775192541
Signed-off-by: Carlos Llamas <cmllamas@google.com>