Kleaf: Fix auto_download_config workflow
This fixes the following error when `auto_download_config` is set:
```
ERROR: <builtin>: fetching kernel_prebuilt_repo rule //:kleaf~~kernel_prebuilt_ext~gki_prebuilts: Traceback (most recent call last):
	File ".../kleaf/impl/kernel_prebuilt_repo.bzl", line 168, column 35, in _kernel_prebuilt_repo_impl
		download_configs = json.decode(repository_ctx.attr.download_configs)
Error in decode: at offset 0, unexpected end of file
```

Fixes: f389785c30ad ("kleaf: [REFACTOR] Clean up kernel_prebuilt_repo (merge)")
Bug: 291918087
Change-Id: Ibee2d7bd9d132522c5bf5f17999423171bb59630
Signed-off-by: Ulises Mendez Martinez <umendez@google.com>