FROMLIST: cgroup: Fix compilation issue due to cgroup_mutex not being exported
When adding folio_memcg function call in the zram module for
Android16-6.12, the following error occurs during compilation:
ERROR: modpost: "cgroup_mutex" [../soc-repo/zram.ko] undefined!

This error is caused by the indirect call to lockdep_is_held(&cgroup_mutex)
within folio_memcg. The export setting for cgroup_mutex is controlled by
the CONFIG_PROVE_RCU macro. If CONFIG_LOCKDEP is enabled while
CONFIG_PROVE_RCU is not, this compilation error will occur.

To resolve this issue, add a parallel macro CONFIG_LOCKDEP control to
ensure cgroup_mutex is properly exported when needed.

Signed-off-by: gao xu <gaoxu2@honor.com>

Bug: 409264079
Link: https://lore.kernel.org/cgroups/24763f5c8a13421fa6dc3672a57a7836@honor.com/T/#u
Change-Id: I5d31371cb216b9aee6eedd5b5e5535ee01d7871d
Signed-off-by: yipeng xiang <yipengxiang@honor.corp-partner.google.com>