Autoupdate of 3 submodules
*build/kernel updated to 01eacb6421b4277e5b71b11c7fe54f22b8ad9b71
kleaf: fix -Wmissing-prototypes errors

Add headers for missing prototypes and tag static functions on multiple
ddk examples to fix several -Wmissing-prototypes issues such as:

  ddk_library/libfoo/foo.c:24:6: error: no previous prototype for function 'foo' [-Werror,-Wmissing-prototypes]
     24 | void foo(void) {}
        |      ^

Fixes: 3a33769174d0 ("kleaf: Add DDK examples.")
Change-Id: I8e8a7c80f3fedcf55a409aa05f75e399da2c85e5
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*common updated to 532bb17ab5dfef4ffab916e3e0343e009cbad80a
Reapply "Makefile.extrawarn: turn on missing-prototypes globally"

This reverts commit 635125d40a11db7157126e87d39b9277297bae76. The issues
exposed by these flags are now resolved and the original commit can be
reapplied now. This avoids further merge conflicts with mainline.

Change-Id: I49b8126bbd3a77f8dcc711c1abbe82602b49fcb7
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*common-modules/virtual-device updated to 74674cf271590d3b1e57d896b42c508b951b2a8d
kleaf: fix -Wmissing-prototypes errors

Add missing prototypes and tag several functions as 'static' to fix
mulitple -Wmissing-prototypes issues such as:

  common-modules/virtual-device/kleaf_test/assembly_test/empty_module.c:24:6: error: no previous prototype for function 'bar' [-Werror,-Wmissing-prototypes]
     24 | void bar(void) {
        |      ^

Change-Id: Ifdab9a997276cb15f55492714711bd4bc00c6da9
Signed-off-by: Carlos Llamas <cmllamas@google.com>