ANDROID: GKI: arm64: Update ABI
Update ABI to fix broken aarch64 build:

ERROR: Report summary:

type 'struct kvm_iommu_driver' changed
  member 'u64 __kabi_reserved1' was removed
  member 'union { int(* get_iommu_endpoint)(struct of_phandle_args*, u64*); struct { u64 __kabi_reserved1; }; union { }; }' was added

Bug: 549621733
Change-Id: I521df13faceb72d61d1f55663ed471692a6faf2d
Signed-off-by: Bartłomiej Grzesik <bgrzesik@google.com>