Kleaf: Remove non-existent attr from kernel_prebuilt_repo
* It fixes the error:
```
...kleaf/impl/declare_kernel_prebuilts.bzl", line 87, column 39, in _declare_repos
	mandatory = module_tag.mandatory,
Error: unknown attribute mandatory
```

Fixes: f389785c30ad ("kleaf: [REFACTOR] Clean up kernel_prebuilt_repo (merge)")
Bug: 291918087
Change-Id: I816891ddc009c12e975856aa6f0a9eea34dbd09c
Signed-off-by: Ulises Mendez Martinez <umendez@google.com>