ANDROID: kleaf: select uapi headers for parse_vdso
Upstream commit c9fbaa879508 ("selftests: vDSO: parse_vdso: Use UAPI
headers instead of libc headers") updated parse_vdso.c kselftest to use
the uapi headers due to new definitions usage. Corresponding updates to
the header inclusion are required for kleaf in order to avoid similar
issues:

  common/tools/testing/selftests/vDSO/parse_vdso.c:62:2: error: unknown type name 'Elf32_Versym'; did you mean 'Elf32_Sym'?
     62 |         ELF(Versym) *versym;
        |         ^~~~~~~~~~~
        |         Elf32_Sym

Bug: 409543119
Cc: Yifan Hong <elsk@google.com>
Fixes: c9fbaa879508 ("selftests: vDSO: parse_vdso: Use UAPI headers instead of libc headers")
Co-developed-by: Tudor Ambarus <tudordana@google.com>
Change-Id: I219816bc0f4bbac5728908cd370b45ae7c0b0fcc
Signed-off-by: Carlos Llamas <cmllamas@google.com>