ANDROID: scmi_cpufreq: Fix uninitialized variable
Commit 85e3a67903c7 ("ANDROID: scmi_cpufreq: Add restricted vendor hook for scmi_limit_notify_cb")
introduced a variable to scmi_limit_notify_cb without initializing it,
causing the following KernelCI build errors:

/tmp/kci/linux/drivers/cpufreq/scmi-cpufreq.c: In function ‘scmi_limit_notify_cb’:
/tmp/kci/linux/drivers/cpufreq/scmi-cpufreq.c:194:12: error: ‘done’ is used uninitialized [-Werror=uninitialized]
  194 |         if (done)
      |            ^
/tmp/kci/linux/drivers/cpufreq/scmi-cpufreq.c:189:14: note: ‘done’ was declared here
  189 |         bool done;
      |              ^~~~
cc1: all warnings being treated as errors

Fix these by initializing done.

Fixes: 85e3a67903c7 ("ANDROID: scmi_cpufreq: Add restricted vendor hook for scmi_limit_notify_cb")
Change-Id: I9d11d34ce1b4649e4eeca1481311028e6267ed19
Signed-off-by: Tiffany Yang <ynaffit@google.com>