ANDROID: dm-user: remove unused function
Fix the following:

drivers/md/dm-user.c:278:30: error: unused function 'target_from_miscdev' [-Werror,-Wunused-function]
  278 | static inline struct target *target_from_miscdev(struct miscdevice *miscdev)
      |                              ^~~~~~~~~~~~~~~~~~~

Bug: 195310033
Fixes: 83bf345abc0b ("ANDROID: dm: dm-user: New target that proxies BIOs to userspace")
Change-Id: Ibeef6385b3beccef8c2c7880aa15f21e23d50df3
Signed-off-by: Eric Biggers <ebiggers@google.com>