ANDROID: GKI: arm64: Update ABI
Update ABI to fix broken aarch64 build:

ERROR: ABI DIFFERENCES HAVE BEEN DETECTED!
ERROR: Report summary:

function symbol 'int _snd_ctl_add_follower(struct snd_kcontrol*, struct snd_kcontrol*, unsigned int)' changed
  CRC changed from 0xf6b1a369 to 0x264a918f

function symbol 'int snd_component_add(struct snd_card*, const char*)' changed
  CRC changed from 0xdc8b3501 to 0xc9f8b252

function symbol 'int snd_ctl_add_vmaster_hook(struct snd_kcontrol*, void(*)(void*, int), void*)' changed
  CRC changed from 0x8ac14ca4 to 0x901d422d

... 5 omitted; 8 symbols have only CRC changes

Bug: none
Test: tools/bazel run //common:kernel_aarch64_abi_update
Change-Id: Ie4941511089d21e07c3244db82a597e37b77cc17
Signed-off-by: Dmytro Maluka <dmaluka@google.com>