ANDROID: fix missing struct cma declaration
A vendor hook using 'struct cma' was added to hooks/mm.h without a
forward declaration. This causes build failures particularly when
DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT is set.

  ./include/trace/hooks/mm.h:288:18: error: declaration of 'struct cma' will not be visible outside of this function [-Werror,-Wvisibility]
  288 |         TP_PROTO(struct cma *cma, const struct page *pages, unsigned long count,
      |                         ^

Add the missing forward declaration.

Bug: 493639986
Fixes: a67968bd9918 ("ANDROID: GKI: add vendor hooks for memory compaction and cma free.")
Change-Id: I88f2aa65673199f19c97752f0527677cfca0edfc
Signed-off-by: Carlos Llamas <cmllamas@google.com>