virtual_device: add font.ko to virtual_device_arm
FONT_SUPPORT gets selected when VIDEO_VIVID=m and for arm 32bit builds
this config moves from FONT_SUPPORT y -> m. The generated 'font.ko'
module then needs to be listed for the virtual_device_arm module outs.
This fixes the following build error:

  ERROR: The following kernel modules are built but not copied. [...]
    "lib/fonts/font.ko",

Cc: Ricardo Ribalda <ribalda@google.com>
Cc: Alistair Delva <adelva@google.com>
Test: bazel run //common-modules/virtual-device:virtual_device_arm_dist
Fixes: 33400d9 ("virtual_device: Add vivid")
Change-Id: Ic157a8ef742551a117fbe7908948c84e1cb664f9
Signed-off-by: Carlos Llamas <cmllamas@google.com>