ANDROID: fix kernelci build break: redefinition of 'kallsyms_on_each_symbol'
An extra definition of the function 'kallsyms_on_each_symbol' crept in
for the !KALLSYMS case as a result as part of the 5.10.220 merge.

kbuild.compiler.error ./include/linux/kallsyms.h:167:19: error: redefinition
of 'kallsyms_on_each_symbol' in arch/x86/kernel/asm-offsets.s (arch/x86/kernel/asm-offsets.c)

Removed obsolete declaration.

Fixes: c4f41ad97060 ("Revert "Merge 5.10.220 into android13-5.10-lts"")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: Ieb332a4693aa3f1123e74a719d46fc9e1d083eda