ANDROID: usb: gadget: configfs: fix -Wmissing-prototypes errors
Add missing 'static' keyword to several functions. This resolves build
issues after enabling -Wmissing-prototypes such as the following:

  common/drivers/usb/gadget/android_configfs_uevent.c:231:6: error: no previous prototype for function '__android_set_connected' [-Werror,-Wmissing-prototypes]
    231 | void __android_set_connected(struct android_uevent_opts *opts,
        |      ^

Cc: Neill Kapron <nkapron@google.com>
Fixes: 957b40b3b769 ("ANDROID: usb: gadget: configfs: Add Uevent to notify userspace")
Change-Id: I074195319b609e7b8c3fb83dd628c4f3fc73e286
Signed-off-by: Carlos Llamas <cmllamas@google.com>