Autoupdate of 14 submodules
*gs/google-modules/amplifiers updated to c8f5cc680113e9d2d5d50dd950c10f698defa8b8
Merge aosp/android-gs-raviole-5.10-android12-qpr3 into aosp/android13-gs-raviole-5.15

* aosp/android-gs-raviole-5.10-android12-qpr3:
  amcs: fix stack buffer OOB write vulnerability
  amcs: fix stack buffer OOB write vulnerability
  cs40l26: merge CirrusLogic cs40l26 v3.0.3
  cs40l26: merge CirrusLogic dsp v3.1.3 and cs40l26 v2.0.1
  cs35l41: add cs35l41_component_ignore_suspend
  cs40l26: Add the RX slots control function back
  cs40l26: merge CirrusLogic dsp v3.1.2 and cs40l26 v1.1.0

Change-Id: I798db898e6bfa13462d5f021d53a5b997e343813
Signed-off-by: Will McVicker <willmcvicker@google.com>

*gs/google-modules/aoc updated to 311c1a5720044e5f69f882faf780e6e7fb1cab8d
Merge aosp/android-gs-raviole-5.10-android12-qpr3 into aosp/android13-gs-raviole-5.15

* aosp/android-gs-raviole-5.10-android12-qpr3:
  aoc: usb: support direct USB access
  aoc: update aoc-interface.h to match the firmware 8184160
  aoc: Add sysfs node for AoC UDFPS clock compensation
  aoc/alsa: use system_highpri_wq for aoc_pcm_period_work
  aoc/alsa: use system_highpri_wq for aoc_pcm_period_work
  aoc: usb: notify AoC if xhci driver is active
  aoc: usb: notify AoC if xhci driver is active
  aoc/alsa: extend aoc command timeout time
  aoc/alsa: extend aoc command timeout time
  aoc: update aoc-interface.h to match the firmware 7987356
  aoc: update aoc-interface.h to match the firmware 7987356
  aoc: fix aoc process hit null pointer
  aoc/alsa: remove the ack function
  Revert "aoc: fix aoc process crash issue when aoc service off"
  aoc: usb: prevent a dereference in free_transfer_ring
  aoc: fix aoc process crash issue when aoc service off
  aoc: usb: remove offload reset process
  aoc: usb: xhci: fix argument errors for xhci decode functions
  Revert "aoc: usb: introduce the mutex lock for remove hcd"
  aoc: usb: xhci: fix argument errors for xhci decode functions
  aoc: add protection if access service without init
  aoc: reset aoc if there is no respond after init aoc
  aoc/alsa: return the heap address for mmap use cases
  aoc/alsa: return the heap address for mmap use cases
  aoc: update aoc-interface.h to match the firmware 7814741
  aoc: update aoc-interface.h to match the firmware 7814741
  Always unlock the AoC memory on restart
  aoc: add error handle to prevent NULL pointer
  aoc: add mutex protect on aoc suspend resume
  aoc: update aoc-interface.h to match the firmware 7753848
  aoc: update aoc-interface.h to match the firmware 7753848
  aoc: correct IRQ status setting
  Revert "Revert "Wait until AoC has powered on before registering the watchdog interrupt""
  Revert "Wait until AoC has powered on before registering the watchdog interrupt"
  Wait until AoC has powered on before registering the watchdog interrupt
  aoc: remove SRAM repaired print
  aoc/asla: change the delay time to 150ms for offload gain reset
  aoc: usb: enable USB3 audio offload
  aoc/asla: change the delay time to 100ms for offload gain reset

Change-Id: I4f33176e8fc1c7c9846b47d4f278ec7f89648d80
Signed-off-by: Will McVicker <willmcvicker@google.com>

*gs/google-modules/bms updated to 7ed7c68bda45715d49b1a49dcfb503be346ded9c
kleaf: add missing google_dock.ko

This was missing from the merge commit.

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: I5e0a8ca2a5e4b11b7f3f64c5a0fa4d537a3bf003

*gs/google-modules/display updated to 9fe22a7a70cdc6647089e50b51cebbf6766c4480
Merge aosp/android-gs-raviole-5.10-android12-qpr3 into aosp/android13-gs-raviole-5.15

* aosp/android-gs-raviole-5.10-android12-qpr3:
  drm: samsung: Don't return error if RX fifo is not empty
  drm: samsung: add lock when dumping dpu event logs
  drm: samsung: allow enabling vblank while entering hibernation
  drm: samsung: add debugfs feature to force TE irq to always enabled
  panel: s6e3hc3: add force changeable TE debug
  panel: s6e3hc3: throttle auto mode when idle_delay is set
  panel: common: add option to delay idle based mode sets
  drm: panel: s6e3hc3: implement minimum idle refresh rate
  panel: create sysfs nodes, min_vrefresh and delay_idle_ms
  drm: samsung: support more configurations of dsc encoder
  drm: samsung: don't enable disp_dither if in_bpc equal to out_bpc
  drm: samsung: recalculate underrun LP time when switching mode
  drm: samsung: move vblank_usec to dpu_bts
  6e3hc3: fine-tune AoD command sequence.
  samsung: panel: update hdr info
  panel: s6e3hc3: vote for 120hz when exiting self refresh
  panel: s6e3hc3: vote for 120hz when exiting self refresh
  drm: samsung: support reversed dual dsi ports
  drm: samsung: support dual dsi
  s6e3hc3: bundle brightness update with HBM update
  drm: samsung: fixed wrong shadow mode configuration of dsim
  samsung: panel: add the definition for panel EVT1.2
  drm: samsung: don't dump debug info if fs irq pending was set
  s6e3hc3: modify HBM on command sequence for EVT1.1 and after
  drm: samsung: move recovery work out of decon kthread
  panel: add constraints for updating TE2
  panel: call common revision function in each panel file
  drm: samsung: extend the time of higher FPS while changing BTS
  drm: samsung: set power.must_resume to true in the suspend path
  s6e3hc3: not enable auto mode/early exit when dimming on
  s6e3hc3: add update frequency in HBM operation
  panel: add IR compensation into the hbm mode attribute
  samsung: panel: support backlight device phandle
  panel: samsung: support custom panel id reading function
  panel: s6e3hc3: vote for 120hz while system resumes
  panel: avoid setting the same mode and TE2
  samsung: panel: make sure LHBM is off before enter AOD

Change-Id: Ib23d3535a495bced0496c8b78df06e39c497bb46
Signed-off-by: Will McVicker <willmcvicker@google.com>

*gs/google-modules/edgetpu updated to 62f7c878b0842070bda13935aff2541463357357
Update the Kbuild file to fix header includes

To include the soc/gs headers we are using EXTRA_CFLAGS in the Makefile.
One caveat with this is that ccflags-y is checked first before
EXTRA_CFLAGS. For this project, we have some header stubs under
include/linux which are added in Kbuild using ccflags-y. This means that
the stubs are actually getting used instead of the real headers from
private/google-modules/soc/gs/include. So fix the Kbuild to remove the
local includes for all but the trace header in order to properly include
the real kernel headers.

This fixes PM stability and firmware loading issues on this branch. Here
are the logs observed:

  I edgetpu_platform 1ce00000.abrolhos: Initial power state: 2
  E edgetpu_platform 1ce00000.abrolhos: pm_runtime_get_sync returned 1
  I edgetpu abrolhos: Powering up
  E edgetpu abrolhos: edgetpu_ioctl_finalize_group: pm_get failed (1)

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: I7984d61f38932ac27f9ce2a8bb31481f3c27e3a8

*gs/google-modules/gpu updated to e3973d6cb0323e3753b4edd5525ad465e91f851a
Merge aosp/android-gs-raviole-5.10-android12-qpr3 into aosp/android13-gs-raviole-5.15

* aosp/android-gs-raviole-5.10-android12-qpr3:
  GPUCORE-32592 Fix userbuf imports to respect RO memory
  mali_kbase: platform: dvfs: Take lock on init
  mali_kbase: platform: power: Explicitly track GPU power state
  Revert "mali_kbase: platform: power: Retry if not powered on"
  mali_kbase: platform: power: Prevent races on power down
  mali_kbase: platform: power: Retry if not powered on

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: I3b0835af17a625567e9326d87c17fbdea6b43742

*gs/google-modules/lwis updated to 8bdf9b6345a46aa0197052d7b5adf5fde7bef25d
Merge aosp/android-gs-raviole-5.10-android12-qpr3 into aosp/android13-gs-raviole-5.15

* aosp/android-gs-raviole-5.10-android12-qpr3:
  Transaction: Use high priority workqueues for I2C
  Periodic: add error handling for integer overflow
  Ioctl: add error handling for integer overflow
  Top: add error handling for integer overflow
  I2C: Fix variable initializations
  Fix uninitialized variables
  Debug: Fix potential null pointer dereferences
  Device: declare device as specific acccess mode
  LWIS: Remove unsupported platform
  LWIS: Remove unsupported platform
  LWIS: Properly support fw_devlink for regulator instances
  Buffer: Print enrolled buffer size when OOM
  LWIS: Run the rest of the commands in cleanup transaction when error
  DT: Free critical event array after use
  Revert "lwis: irq: restrict camera irq affinity to high level core"
  lwis: irq: restrict camera irq affinity to high level core
  LWIS: Enable enrolling buffers of the same vaddr more than once.

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Ia85fd677452f8e0d4315b8723ecd72685cd4d9c9

*gs/google-modules/power/reset updated to 9db1a257ad08dbaf9566693c6a9383a9460f28b9
Merge aosp/android-gs-raviole-5.10-android12-qpr3 into aosp/android13-gs-raviole-5.15

* aosp/android-gs-raviole-5.10-android12-qpr3:
  power: reset: add in_panic and in_warm for swreset
  power: reset: support emergency_restart swreset

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Ie9b93464813f974542185aabc3061865af522078

*gs/google-modules/soc-modules updated to d9c772415d784cbd91b2cd6c4002e10f8447d2d1
tcpci_max77759: move max77759_export.h to include/linux/usb

This is needed for external modules as well. So make is accessible.

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Ifed9de39a03c211f4364f58c55ee26bf5b13a95f

*gs/google-modules/touch/common updated to 9c70325e9ab16d952a4ab097988c7d21a943d0f4
Merge aosp/android-gs-raviole-5.10-android12-qpr3 into aosp/android13-gs-raviole-5.15

* aosp/android-gs-raviole-5.10-android12-qpr3:
  input: touch_offload: interface updates
  touch: common: fix build break
  touch_offload: create touch_offload devices with unique names

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: I085b3ed9458f3d583568ab2837acd1fea07da672

*gs/google-modules/touch/fts updated to 14ec96751820938cffdbbd02af0850574f9d3797
Merge aosp/android-gs-raviole-5.10-android12-qpr3 into aosp/android13-gs-raviole-5.15

* aosp/android-gs-raviole-5.10-android12-qpr3:
  touch: fts: Clear input directly when offload isn't running.
  ftm5: dump heatmap when get stuck in the plam mode
  touch: fts: support rotation reporting
  touch/ftm5: Push frame with empty coords on suspend.
  ftm5: fix the touch_offload major/minor scale
  ftm5: Fix inversion and heatmap dimensions
  ftm5: create unique touch offload device name
  ftm5: Skip boot-time FPI for factory build MP flag 0x00
  fst2: update driver to version 6.0.4
  touch: fst2: add input device unique ID
  touch: fst2: enable touch controller interrupt
  touch: fst2: correct the touch resolution
  touch: fst2: use drm bridge for touch suspend/resume
  touch: fst2: change log format
  touch: fst2: change driver name
  touch: fst2: modify the way to parse regulator
  touch: fst2: fix build break
  touch: fst2: add initial driver

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: I4cb6c7b16dc5833014ff2c6a9465cac7cf8d8209

*gs/google-modules/touch/sec updated to dbb588539d752dbdf9a0528be62502eb0650ae54
touch/sec: Fix warning caused by not checking return value

sec_ts.c:1879:2: error: ignoring return value of function declared with
'warn_unused_result' attribute [-Werror,-Wunused-result]
      kfifo_out_peek(&debug_fifo, last_coord, kfifo_size(&debug_fifo));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: I46f45e73156b5742a762054e9e70bad957d1b335

*gs/google-modules/uwb updated to 9e433d655dcbf751c1c85553c5d986f4271b4ca6
Merge aosp/android-gs-raviole-5.10-android12-qpr3 into aosp/android13-gs-raviole-5.15

* aosp/android-gs-raviole-5.10-android12-qpr3:
  dw3000: rework stm locking strategy
  CCC Deep sleep can now be controlled by the UWB-claibration.conf parameter.
  dw3000: rework stm locking strategy
  mac: ensure consistency between pib and llhw channel info
  dw3000: ensure supported channels correctly updated
  Revert "dw3000_stm: uninterruptedly wait for pending_work to complete"
  ccc: integrate nfcc v2
  Add Block Striding support
  Revert "dw3000_stm: uninterruptedly wait for pending_work to complete"
  dw3000_stm: uninterruptedly wait for pending_work to complete
  dw3000: rework deep sleep according dwt driver, refs UWB-1877
  dw3000: rework deep sleep according dwt driver, refs UWB-1877
  dw3000_stm: uninterruptedly wait for pending_work to complete

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Ib9bb758944ffcdaeec11050e27b0c8414f586f76

*gs/google-modules/wlan/bcmdhd4389 updated to 49b1c8ef9249cdd697827cc1e8f380d36414f831
Fix build issues related to the merge

Fixes modified function definitions.

Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Ie53c3978ad8362c3f84b748aa7b462bc33c529bc