ANDROID: sched: Fix kernelci build-break: undefined symbol
Fix incorrectly #ifdef'd call to 'stack_trace_save_tsk()'

kernel/sched/core.c: In function ‘__schedule’:
kernel/sched/core.c:7726:25: error: implicit declaration of function ‘stack_trace_save_tsk’ [-Wimplicit-function-declaration]
 7726 |                         stack_trace_save_tsk(prev, &blocked_func, 1, 0);
      |                         ^~~~~~~~~~~~~~~~~~~~

Found in 32-bit arm allmodconfig build by kernelci

Fixes: b24c1517d9cc ("ANDROID: Fix invalid caller output in trace_sched_blocked_reason")
Signed-off-by: Todd Kjos <tkjos@google.com>
Change-Id: I04937654d569494612bfaf00a7203c24a77528fd