Autoupdate of 2 submodules
*common updated to b519faae301eec9c18ee39da29d4f070c8d0a831
ANDROID: ABI: gki_defconfig: disable cfg80211 and mac80211

Remove CONFIG_CFG80211 and CONFIG_MAC80211 from gki_defconfig
to allow vendors to incorporate features that lands upstream
after KMI freeze.

Also need to update symbol lists since the related 80211
symbols are no longer exported from the core kernel.

Bug: 227176212
Test: TH
Signed-off-by: Ramji Jiyani <ramjiyani@google.com>
Change-Id: Ia680c2b38d5f13263e318f8c5eaa42f591385736
(cherry picked from commit b24cd8be89c6b6ede275e63d2ce44f6735864236)
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*common-modules/virtual-device updated to 10e793aa13366557576d47448778a369203b76ea
kleaf: add cfg80211 and mac80211 to module_outs

These modules are missing from the module_outs list yet are enabled as
vendor modules. Adding them fixes the follwing build issue:

  ERROR: The following kernel modules are built but not copied. [...]
    "net/wireless/cfg80211.ko",
    "net/mac80211/mac80211.ko",

Bug: 239479410
Test: bazel run //common-modules/virtual-device:virtual_device_x86_64
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I4bb2a2f7f0a5c538c406b95d387b6fce38091957