Kleaf: Make kernel_build.make_goals required
Commit b10158c0cc39 ("Kleaf: Make kernel_build.make_goals mandatory")
made this attribute mandatory for the kernel_env rule, however this
change goes one step up and makes it required at the kernel_build macro
level, which makes it easier for a user to spot what is missing, becuase
it prints the following error when not specified:

`Error: kernel_build() missing 1 required positional argument: make_goals`

Bug: 495914929
Change-Id: I052f3c5f14c051bbc336232b570d9a527136b32a