mali_kbase_sync_file.c: delete unused variable
to resolve the build error reported like this:

/oe/common/../hikey-modules/midgard/mali_kbase_sync_file.c:70:6: error: unused variable 'fd' [-Werror,-Wunused-variable]
        int fd;
            ^
1 error generated.

Fixes: a87c181b5773 ("MALI: Drop use of ksys_close(), rework fd_install usage")
Fixes: 824c55581dde ("UPSTREAM: Enable '-Werror' by default for all kernel builds")
Test: build successfully

Change-Id: Ida6c963e7b6ec0e57149ffb50a931f56533a87f9
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>