net-test: adjust for 6.6+
I'm not 100% sure this is a good idea or not (which is why it is UML only), but due to:
  commit c0236846aff5874422b787c163f2650971521b94 (HEAD)
  Author: Eric Dumazet <edumazet@google.com>
  Date:   Mon Jul 17 15:29:17 2023 +0000

  tcp: get rid of sysctl_tcp_adv_win_scale

net-test (sock_diag_test.py) currently fails with:

  FAIL: testTcpCwndSize (__main__.TcpRcvWindowTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/host/mnt/zoom/maze/aosp-tests/net/test/./sock_diag_test.py", line 559, in testTcpCwndSize
      self.checkInitRwndSize(version, netid)
    File "/host/mnt/zoom/maze/aosp-tests/net/test/./sock_diag_test.py", line 537, in checkInitRwndSize
      self.assertLess(self.RWND_SIZE, tcpInfo.tcpi_rcv_ssthresh,
  AssertionError: 64000 not less than 31820 : Tcp rwnd of netid=100, version=4 is not enough. Expect: 64000, actual: 31820

The test can be summarized as:
  self.IncomingConnection(version, TCP_ESTABLISHED, netid)
  tcpInfo = TcpInfo(self.accepted.getsockopt(SOL_TCP, TCP_INFO, len(TcpInfo)))
  self.assertLess(64000, tcpInfo.tcpi_rcv_ssthresh, ...)

and appears to be related to some no longer present Android only sysctl
for increasing initial receive window size.

Note: not clear why increasing tcp_rmem_default by a factor of 2,
increases rwin from 31820 to 64000+ (which is more than 2x).

Test: TreeHugger, UML on net-next/main
Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Ie022f70ef87544877906cdc7a319b5abfb9f031c