Autoupdate of 2 submodules
*common-mainline updated to 532bb17ab5dfef4ffab916e3e0343e009cbad80a
Reapply "Makefile.extrawarn: turn on missing-prototypes globally"

This reverts commit 635125d40a11db7157126e87d39b9277297bae76. The issues
exposed by these flags are now resolved and the original commit can be
reapplied now. This avoids further merge conflicts with mainline.

Change-Id: I49b8126bbd3a77f8dcc711c1abbe82602b49fcb7
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*common-modules/virtual-device-mainline updated to 74674cf271590d3b1e57d896b42c508b951b2a8d
kleaf: fix -Wmissing-prototypes errors

Add missing prototypes and tag several functions as 'static' to fix
mulitple -Wmissing-prototypes issues such as:

  common-modules/virtual-device/kleaf_test/assembly_test/empty_module.c:24:6: error: no previous prototype for function 'bar' [-Werror,-Wmissing-prototypes]
     24 | void bar(void) {
        |      ^

Change-Id: Ifdab9a997276cb15f55492714711bd4bc00c6da9
Signed-off-by: Carlos Llamas <cmllamas@google.com>