ANDROID: kleaf: add more sources for kselftests
Upstream 'transhuge_stress' kselftest now uses thp_settings sources to
determine whether thp is available in the system. We need to manually
incorporate these source files to the bazel recipe, so do that.

This patch fixes:
 common/tools/testing/selftests/mm/transhuge-stress.c:20:10: fatal error: 'thp_settings.h' file not found
   20 | #include "thp_settings.h"
      |          ^~~~~~~~~~~~~~~~

Fixes: cfe9a446f519 ("selftests/mm: transhuge_stress: skip the test when thp not available")
Change-Id: Ie7c0609f91817fb492ba33590311b7d0bef0f809
Signed-off-by: Carlos Llamas <cmllamas@google.com>