ANDROID: KVM: arm64: iommu: Fix build errors when CONFIG_CMA is not set
When CONFIG_KVM=y but CONFIG_CMA is not selected, kernelci builds fail
with the following:

    aarch64-linux-gnu-ld: Unexpected GOT/PLT entries detected!
    aarch64-linux-gnu-ld: Unexpected run-time procedure linkages detected!
    aarch64-linux-gnu-ld: arch/arm64/kvm/iommu.o: in function `kvm_iommu_cma_alloc':
    /tmp/kci/linux/arch/arm64/kvm/iommu.c:191:(.text+0x4f4): undefined reference to `cma_alloc'
    aarch64-linux-gnu-ld: arch/arm64/kvm/iommu.o: in function `kvm_iommu_cma_release':
    /tmp/kci/linux/arch/arm64/kvm/iommu.c:200:(.text+0x540): undefined reference to `cma_release'
    aarch64-linux-gnu-ld: arch/arm64/kvm/iommu.o: in function `kvm_iommu_cma_alloc':
    /tmp/kci/linux/arch/arm64/kvm/iommu.c:191:(.text+0x834): undefined reference to `cma_alloc'
    aarch64-linux-gnu-ld: arch/arm64/kvm/iommu.o: in function `kvm_iommu_cma_release':
    /tmp/kci/linux/arch/arm64/kvm/iommu.c:200:(.text+0xa04): undefined reference to `cma_release'
    aarch64-linux-gnu-ld: arch/arm64/kvm/iommu.o: in function `pkvm_iommu_cma_setup':
    /tmp/kci/linux/arch/arm64/kvm/iommu.c:169:(.init.text+0x64): undefined reference to `cma_init_reserved_mem'
    aarch64-linux-gnu-ld: /tmp/kci/linux/arch/arm64/kvm/iommu.c:177:(.init.text+0x90): undefined reference to `cma_get_base'
    aarch64-linux-gnu-ld: /tmp/kci/linux/arch/arm64/kvm/iommu.c:178:(.init.text+0xa0): undefined reference to `cma_get_size'

Use ifdef guards around CMA calls to fix these build errors and compile
out related code.

Bug: 383901011
Bug: 277989609
Bug: 357781595
Fixes: 3f35c377b90d ("ANDROID: KVM: arm64: iommu: Allow donations from a CMA pool")
Fixes: 438604c14d86 ("ANDROID: iommu/arm-smmu-v3-kvm: Always keep a spare block for GFP_ATOMIC case")
Change-Id: I6d10d2c8e51ac414ee10b8b849a9f6dab8751948
Signed-off-by: Tiffany Yang <ynaffit@google.com>