FROMLIST: drm/xe: replace basename() with portable strrchr()
Commit b0a2ee5567ab ("drm/xe: prepare xe_gen_wa_oob to be multi-use")
introduced a call to basename(). The GNU version of this function is not
portable and fails to build with alternative libc implementations like
musl or bionic. This causes the following build error:

  drivers/gpu/drm/xe/xe_gen_wa_oob.c:130:12: error: assignment to ‘const char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
    130 |         fn = basename(fn);
        |            ^

While a POSIX version of basename() could be used, it would require a
separate header plus the behavior differs from GNU version in that it
might modify its argument. Not great.

Instead replace basename() with a strrchr() based implementation which
provides the same functionality and avoid portability issues.

Fixes: b0a2ee5567ab ("drm/xe: prepare xe_gen_wa_oob to be multi-use")
Signed-off-by: Carlos Llamas <cmllamas@google.com>

Link: https://lore.kernel.org/all/20250820201612.2549797-1-cmllamas@google.com/

Bug: 440333928
Upstream-Task: 402479223
Test: Presubmit

(cherry picked from https://android-review.googlesource.com/q/commit:c71ecb422115b1a9571b3e36cf14eb06c8de99c5)
Merged-In: Icb43fd8af1fe25dd8828d3c6d20ec96d8768932f
Change-Id: Icb43fd8af1fe25dd8828d3c6d20ec96d8768932f
Signed-off-by: Sarthak Kukreti <sarthakkukreti@google.com>