ANDROID: binder: Fix build errors from unmet dependencies
Currently, when we build with CONFIG_ANDROID_BINDER_IPC=y without
selecting CONFIG_ANDROID_BINDERFS, we get the following build errors in
kernelci:

  CC      drivers/iio/industrialio-buffer.o
drivers/android/binder.c: In function ‘binder_unload_builtin’:
drivers/android/binder.c:7412:9: error: implicit declaration of function ‘unload_binderfs’; did you mean ‘init_binderfs’? [-Wimplicit-function-declaration]
 7412 |         unload_binderfs();
      |         ^~~~~~~~~~~~~~~
      |         init_binderfs

Add a placeholder definition for unload_binderfs for this case.

Additionally, add EVENT_TRACING as a dependency for ANDROID_BINDER_IPC
since we use event_mutex in binder_pick.
This prevents errors like the following:

drivers/android/binder_pick.c:125:(.text+0x1a0): undefined reference to `event_mutex'
aarch64-linux-ld: drivers/android/binder_pick.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `event_mutex' which may bind externally can not be used when making a shared object; recompile with -fPIC
drivers/android/binder_pick.c:125:(.text+0x1a0): dangerous relocation: unsupported relocation

Bug: 465732281
Fixes: 42393aa5693a ("ANDROID: binder: support loading both drivers at the same time")
Reported-by: kernelci.org bot <bot@kernelci.org>
Closes: https://d.kernelci.org/i/maestro:66ab9de86956b5ca0cdfe62ad74a684954dd64bc
Change-Id: Ibb9cf9fb453ee62f044d8cd12ca3bb0fcfb8db48
Signed-off-by: Tiffany Yang <ynaffit@google.com>