Autoupdate of 5 submodules
*build/kernel updated to 01eacb6421b4277e5b71b11c7fe54f22b8ad9b71
kleaf: fix -Wmissing-prototypes errors

Add headers for missing prototypes and tag static functions on multiple
ddk examples to fix several -Wmissing-prototypes issues such as:

  ddk_library/libfoo/foo.c:24:6: error: no previous prototype for function 'foo' [-Werror,-Wmissing-prototypes]
     24 | void foo(void) {}
        |      ^

Fixes: 3a33769174d0 ("kleaf: Add DDK examples.")
Change-Id: I8e8a7c80f3fedcf55a409aa05f75e399da2c85e5
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*common updated to 532bb17ab5dfef4ffab916e3e0343e009cbad80a
Reapply "Makefile.extrawarn: turn on missing-prototypes globally"

This reverts commit 635125d40a11db7157126e87d39b9277297bae76. The issues
exposed by these flags are now resolved and the original commit can be
reapplied now. This avoids further merge conflicts with mainline.

Change-Id: I49b8126bbd3a77f8dcc711c1abbe82602b49fcb7
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/power/mitigation updated to 8071c2e31ca4792a0295a008669ebd39057cd633
bcl: temporarily disable -Wmissing-prototypes

This flag was recently enabled upstream in commit 0fcb70851fbf
("Makefile.extrawarn: turn on missing-prototypes globally"), which
triggers several errors in this repo. Disable the flag temporarily
until the individual issues get fixed.

Bug: 424610699
Change-Id: I927b9218174ef40036bf7455ef18a299836b5154
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/soc/gs updated to 2eeddbf7cb5636eff465b9da89220796e0163d92
kbuild: temporarily disable -Wmissing-prototypes

This flag was recently enabled upstream in commit 0fcb70851fbf
("Makefile.extrawarn: turn on missing-prototypes globally"), which
triggers several errors in this repo. Disable the flag temporarily
until the individual issues get fixed.

Bug: 424610699
Change-Id: Iacc6293fdc5ce9b1e14c3d7eeaf56895b7127c23
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/uwb updated to 6e1101b951565dac846399177d80588fee0f3d62
dw3000: temporarily disable -Wmissing-prototypes

This flag was recently enabled upstream in commit 0fcb70851fbf
("Makefile.extrawarn: turn on missing-prototypes globally"), which
triggers several errors in this repo. Disable the flag temporarily
until the individual issues get fixed.

Bug: 424610699
Change-Id: I1eaa07b3169a6161634251c6048e17114af13d2a
Signed-off-by: Carlos Llamas <cmllamas@google.com>