ANDROID: GKI: fs: Allow configfs to use vfs-only namespace
KernelCI armv5 builds fail with the following error when configfs is
built as a module:

ERROR: modpost: module configfs uses symbol iunique from namespace ANDROID_GKI_VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module configfs uses symbol d_drop from namespace ANDROID_GKI_VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.
ERROR: modpost: module configfs uses symbol generic_read_dir from namespace ANDROID_GKI_VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver, but does not import it.

Fix this by importing
ANDROID_GKI_VFS_internal_I_am_really_a_filesystem_and_am_NOT_a_driver
where the relevant functions are used.

Fixes: fd2cbc1b7ab7 ("ANDROID: GKI: set vfs-only exports into their own namespace")
Reported-by: kernelci.org bot <bot@kernelci.org>
Closes: https://d.kernelci.org/i/maestro:40963bed4a8ddb0f7f18882babcfe876a844f49d
Change-Id: I597b736843806ce6e6c0af39a4f23843a20b4028
Signed-off-by: Tiffany Yang <ynaffit@google.com>