ANDROID: irqchip/gic-v3: Remove gic_v3_suspend() stub for !CONFIG_PM builds
gic_v3_suspend() does not need to be defined when CONFIG_PM is not
enabled. Doing so causes a build error when building with the
-Werror,-Wunused-function flags as seen below:

drivers/irqchip/irq-gic-v3.c:1586:12: error: unused function 'gic_v3_suspend' [-Werror,-Wunused-function]
 1586 | static int gic_v3_suspend(void) { return 0; }
      |            ^~~~~~~~~~~~~~
1 error generated.

Fix by removing gic_v3_suspend when CONFIG_PM is not defined.

Bug: 433421153
Fixes: bca065e87652 ("ANDROID: irqchip/irq-gic-v3: Add vendor hook for gic suspend")
Change-Id: I2b9262a68cd61f13bddb88a9f200a32d5aeb0f1f
Signed-off-by: Isaac J. Manjarres <isaacmanjarres@google.com>