v4l2loopback: Replace strlcpy() with compatible and safer variant strscpy()
strlcpy() has now been formally removed from the kernel due to the risks it poses.

Fixes the following build error:

  common-modules/virtual-device/v4l2loopback/v4l2loopback.c:906:2: error:
    call to undeclared library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)';
      ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    906 |         strlcpy(cap->driver, "v4l2 loopback", sizeof(cap->driver));
        |         ^

Fixes: 9ad0b05 ("Build v4l2loopback for x86_64 and aarch64")
Change-Id: I4714e26574c1afc848d3493dfaf52be51a9ca026
Signed-off-by: Lee Jones <joneslee@google.com>