ANDROID: Fix allmodconfig warning caused by the missing label
Reverting cleancache patchset [1] introduced an old label which was
removed in the recent kernels. This causes a new warning:

fs/btrfs/extent_io.c:1003:9: error: use of undeclared label 'out'
 1003 |                         goto out;

Fix it by an equivalent return.

[1] ANDROID: Revert "mm: remove cleancache"

Test: tools/bazel build --allow_undeclared_modules --nowarn_undeclared_modules //common:kernel_arm_allmodconfig
Bug: 327637996
Bug: 323283126
Change-Id: I7204ed98b55a4441f640d2497d53fed92b45e1b5
Signed-off-by: Suren Baghdasaryan <surenb@google.com>