Merge tag 'android12-5.10.240_r00' into android12-5.10
This merges the android12-5.10.240_r00 tag into the android12-5.10 branch,
catching it up with the latest LTS releases.

It contains the following commits:

* badf54d0b8cd Merge android12-5.10 into android12-5.10-lts
* d32c80babba3 Revert "vm_sockets: Add flags field in the vsock address data structure"
* 75080868be35 Revert "vm_sockets: Add VMADDR_FLAG_TO_HOST vsock flag"
* 3a75dfd50a1c Revert "af_vsock: Set VMADDR_FLAG_TO_HOST flag on the receive path"
* f46b1927af73 Revert "af_vsock: Assign the vsock transport considering the vsock address flags"
* d1d6db1a2b0d Revert "vsock: Fix transport_* TOCTOU"
* cab4cd3ccfb7 Merge 5.10.240 into android12-5.10-lts
* d5eca7ebcf6f Linux 5.10.240
* 48900d839a34 rseq: Fix segfault on registration when rseq_cs is non-zero
* a8a08f1e519b x86/process: Move the buffer clearing before MONITOR
* 6fea1a4e150f KVM: SVM: Advertise TSA CPUID bits to guests
* 6457a8c0a026 KVM: x86: add support for CPUID leaf 0x80000021
* 78192f511f40 x86/bugs: Add a Transient Scheduler Attacks mitigation
* b9d08aebbe18 x86/bugs: Rename MDS machinery to something more generic
* 155d13caada0 x86/mm: Disable hugetlb page table sharing on 32-bit
* 80cf68489681 vhost-scsi: protect vq->log_used with vq->mutex
* 3eba9ff0874c Input: atkbd - do not skip atkbd_deactivate() when skipping ATKBD_CMD_GETID
* 7ac00f019698 HID: quirks: Add quirk for 2 Chicony Electronics HP 5MP Cameras
* c8b516a686ef HID: Add IGNORE quirk for SMARTLINKTECHNOLOGY
* 99e25c7b8350 vt: add missing notification when switching back to text mode
* fd0fe8129255 net: usb: qmi_wwan: add SIMCom 8230C composition
* 8806629f79af um: vector: Reduce stack usage in vector_eth_configure()
* 694e78d3a339 atm: idt77252: Add missing `dma_map_error()`
* 16ae30660216 bnxt_en: Set DMA unmap len correctly for XDP_REDIRECT
* fdf47c29ccd2 bnxt_en: Fix DCB ETS validation
* cb124975e490 net: ll_temac: Fix missing tx_pending check in ethtools_set_ringparam()
* 4c83b70b113c can: m_can: m_can_handle_lost_msg(): downgrade msg lost in rx message to debug level
* 69214734c9ca net: phy: microchip: limit 100M workaround to link-down events on LAN88xx
* a7852b017936 net: appletalk: Fix device refcount leak in atrtr_create()
* 12b00ec99624 md/raid1: Fix stack memory use after return in raid1_reshape
* 014c34dc1320 wifi: zd1211rw: Fix potential NULL pointer dereference in zd_mac_tx_to_dev()
* 6689454d2d04 dma-buf: fix timeout handling in dma_resv_wait_timeout v2
* b51f7e6f691b Input: xpad - support Acer NGR 200 Controller
* a226c3f804c4 Input: xpad - add VID for Turtle Beach controllers
* 0d72bbfeed20 Input: xpad - add support for Amazon Game Controller
* 5db2f768a8f8 netlink: make sure we allow at least one dump skb
* a363f5719d71 netlink: Fix rmem check in netlink_broadcast_deliver().
* 8e221225643c pwm: mediatek: Ensure to disable clocks in error path
* 07e49c6a4f9e rtc: lib_test: add MODULE_LICENSE
* a9c058b0ab50 ethernet: atl1: Add missing DMA mapping error checks and count errors
* 4ea0b1c30257 Revert "ACPI: battery: negate current when discharging"
* d43657b59f36 usb: gadget: u_serial: Fix race condition in TTY wakeup
* e62f51d0ec8a drm/sched: Increment job count before swapping tail spsc queue
* 3f8fc02c2582 pinctrl: qcom: msm: mark certain pins as invalid for interrupts
* 7c0366ccdcce x86/mce: Make sure CMCI banks are cleared during shutdown on Intel
* 8f7851a98c6e x86/mce: Don't remove sysfs if thresholding sysfs init fails
* 0c6bb356c07b x86/mce/amd: Fix threshold limit reset
* 0aac24882272 x86/its: FineIBT-paranoid vs ITS
* 31967b44812d x86/its: Fix build errors when CONFIG_MODULES=n
* ac1b649e46f9 x86/its: Use dynamic thunks for indirect branches
* 852084566b33 x86/modules: Set VM_FLUSH_RESET_PERMS in module_alloc()
* 129947ac5441 x86/its: Add "vmexit" option to skip mitigation on some CPUs
* 116a42f01f7d x86/its: Enable Indirect Target Selection mitigation
* 07d828c08456 x86/its: Fix undefined reference to cpu_wants_rethunk_at()
* f5709d9086f6 x86/its: Add support for ITS-safe return thunk
* d9e2ba542fc2 x86/alternatives: Remove faulty optimization
* ad40aa1f3f10 x86/alternative: Optimize returns patching
* ae00968afde3 x86/its: Add support for ITS-safe indirect thunk
* c06b48bf6649 x86/alternatives: Teach text_poke_bp() to patch Jcc.d32 instructions
* 09c33d19dd4c x86/alternatives: Introduce int3_emulate_jcc()
* 3c9fea6f4649 x86/its: Enumerate Indirect Target Selection (ITS) bug
* 5402d7784a0c x86/bhi: Define SPEC_CTRL_BHI_DIS_S
* cda93610bbbf Documentation: x86/bugs/its: Add ITS documentation
* f7afb3ff01c4 rxrpc: Fix oops due to non-existence of prealloc backlog struct
* 87ed20fb3422 fs/proc: do_task_stat: use __for_each_thread()
* 90436e72c962 net/sched: Abort __tc_modify_qdisc if parent class does not exist
* a16fbe6087e9 atm: clip: Fix NULL pointer dereference in vcc_sendmsg()
* 125166347d56 atm: clip: Fix infinite recursive call of clip_push().
* 9e4dbeee56f6 atm: clip: Fix memory leak of struct clip_vcc.
* 70eac9ba7ce2 atm: clip: Fix potential null-ptr-deref in to_atmarpd().
* 964c7ce78550 net: phy: smsc: Fix link failure in forced mode with Auto-MDIX
* 59d8f05aa85c net: phy: smsc: Fix Auto-MDIX configuration when disabled by strap
* 4328279c6ef1 vsock: Fix IOCTL_VM_SOCKETS_GET_LOCAL_CID to check also `transport_local`
* 8667e8d0eb46 vsock: Fix transport_* TOCTOU
* 833da12eff2e af_vsock: Assign the vsock transport considering the vsock address flags
* 0e7a8ad0d7a4 af_vsock: Set VMADDR_FLAG_TO_HOST flag on the receive path
* 29dbdd234b2c vm_sockets: Add VMADDR_FLAG_TO_HOST vsock flag
* 40e6fbd09c0d vm_sockets: Add flags field in the vsock address data structure
* c5496ee685c4 vsock: Fix transport_{g2h,h2g} TOCTOU
* 15a6f4971e2f tipc: Fix use-after-free in tipc_conn_close().
* c4ceaac5c5ba netlink: Fix wraparounds of sk->sk_rmem_alloc.
* f95a9a0adb5f fix proc_sys_compare() handling of in-lookup dentries
* d7ef1afd5b3f perf: Revert to requiring CAP_SYS_ADMIN for uprobes
* 8f2d162c4bcf ASoC: fsl_asrc: use internal measured ratio for non-ideal ratio mode
* a2130463fc94 drm/exynos: exynos7_drm_decon: add vblank check in IRQ handling
* 416d681f4998 staging: rtl8723bs: Avoid memset() in aes_cipher() and aes_decipher()
* f18d72695d67 media: uvcvideo: Rollback non processed entities on error
* 522eb435aaef media: uvcvideo: Send control events for partial succeeds
* 14154b3e61d2 media: uvcvideo: Return the number of processed controls
* d214ffa6eb39 ACPI: PAD: fix crash in exit_round_robin()
* eb08fca56f1f usb: typec: displayport: Fix potential deadlock
* 4b31e2768555 Logitech C-270 even more broken
* d842e72f3305 xhci: dbc: Flush queued requests before stopping dbc
* 33bd90a58672 xhci: dbctty: disable ECHO flag by default
* fdbf8bcda794 dpaa2-eth: fix xdp_rxq_info leak
* b5207325b550 net: dpaa2-eth: rearrange variable in dpaa2_eth_get_ethtool_stats
* 166ecef0dc13 dpaa2-eth: Update SINGLE_STEP register access
* cb2c378a7e46 dpaa2-eth: Update dpni_get_single_step_cfg command
* d20d07f89fcd dpaa2-eth: rename dpaa2_eth_xdp_release_buf into dpaa2_eth_recycle_buf
* 9672f9f0c1e1 btrfs: use btrfs_record_snapshot_destroy() during rmdir
* b0d162c82b09 btrfs: propagate last_unlink_trans earlier when doing a rmdir
* db5f19a43845 NFSv4/flexfiles: Fix handling of NFS level errors in I/O
* bf79245fa3bc flexfiles/pNFS: update stats on NFS4ERR_DELAY for v4.1 DSes
* a8f6150b053d RDMA/mlx5: Fix vport loopback for MPV device
* 2446e25e9246 drm/v3d: Disable interrupts before resetting the GPU
* d029500c1fe9 mtk-sd: reset host->mrq on prepare_data() error
* d54771571f74 mtk-sd: Prevent memory corruption from DMA map failure
* 7f5475bc136c mmc: mediatek: use data instead of mrq parameter from msdc_{un}prepare_data()
* 9fe71972869f regulator: gpio: Fix the out-of-bounds access to drvdata::gpiods
* e38c1548fcd3 rcu: Return early if callback is not specified
* 2219e49857ff ACPICA: Refuse to evaluate a method if arguments are missing
* e6c49f0b203a wifi: ath6kl: remove WARN on bad firmware input
* d4ccd3b5dadc wifi: mac80211: drop invalid source address OCB frames
* 70ddb8133fdb scsi: target: Fix NULL pointer dereference in core_scsi3_decode_spec_i_port()
* d50e80f6f992 powerpc: Fix struct termio related ioctl macros
* fd2560c2df5a ata: pata_cs5536: fix build on 32-bit UML
* e1c4e5409d90 ALSA: sb: Force to disable DMAs once when DMA mode is changed
* e9921b57dca0 net/sched: Always pass notifications when child class becomes empty
* c125405b57e4 nui: Fix dma_mapping_error() check
* fe62a35fb1f7 rose: fix dangling neighbour pointers in rose_rt_device_down()
* eed1f9abbeb1 net: rose: Fix fall-through warnings for Clang
* 2573fedb9bb7 enic: fix incorrect MTU comparison in enic_change_mtu()
* aec3bf6fef49 amd-xgbe: align CL37 AN sequence as per databook
* 669d19a5a397 lib: test_objagg: Set error message in check_expect_hints_stats()
* e47d7d6edc40 drm/i915/gt: Fix timeline left held on VMA alloc error
* 3f4411247e01 drm/i915/selftests: Change mock_request() to return error pointers
* c4446723f4c2 spi: spi-fsl-dspi: Clear completion counter before initiating transfer
* 52e068f63de6 drm/exynos: fimd: Guard display clock control with runtime PM calls
* 52f8a4fdc2a5 btrfs: fix missing error handling when searching for inode refs during log replay
* 070c8c2d3da9 RDMA/mlx5: Fix CC counters query for MPV
* 2baca6a2ed34 scsi: ufs: core: Fix spelling of a sysfs attribute name
* 96a6d229b80a scsi: qla4xxx: Fix missing DMA mapping error in qla4xxx_alloc_pdu()
* 0fff13f36ea0 scsi: qla2xxx: Fix DMA mapping test in qla24xx_get_port_database()
* 08287df60bac NFSv4/pNFS: Fix a race to wake on NFS_LAYOUT_DRAIN
* 412534a1fb76 nfs: Clean up /proc/net/rpc/nfs when nfs_fs_proc_net_init() fails.
* 972e968aac0d RDMA/mlx5: Initialize obj_event->obj_sub_list before xa_insert
* df060fb0d038 platform/mellanox: mlxbf-tmfifo: fix vring_desc.len assignment
* d22e6c8ffe31 mtk-sd: Fix a pagefault in dma_unmap_sg() for not prepared data
* 114a977e0f6b usb: typec: altmodes/displayport: do not index invalid pin_assignments
* 8ac2f131ca07 Revert "mmc: sdhci: Disable SD card clock before changing parameters"
* 8b62c6894c36 mmc: sdhci: Add a helper function for dump register in dynamic debug mode
* 1c1bcb0e7823 vsock/vmci: Clear the vmci transport packet properly when initializing it
* ee1f5d187ea5 rtc: cmos: use spin_lock_irqsave in cmos_interrupt
* 1fee82cc25c8 arm64: Restrict pagetable teardown to avoid false warning
* 3881c1936af2 Revert "ipv6: save dontfrag in cork"
* a2893d3caa14 s390: Add '-std=gnu11' to decompressor and purgatory CFLAGS
* 54dbe61b1590 PCI: hv: Do not set PCI_COMMAND_MEMORY to reduce VM boot time
* d079c09e4f47 drm/bridge: cdns-dsi: Wait for Clk and Data Lanes to be ready
* eda2c25ad3c2 drm/bridge: cdns-dsi: Check return value when getting default PHY config
* dc77f4f01b24 drm/bridge: cdns-dsi: Fix connecting to next bridge
* 130eca8ce97c drm/bridge: cdns-dsi: Fix the clock variable for mode_valid()
* 72afc9635eb3 drm/amdkfd: Fix race in GWS queue scheduling
* f03b2a15025e drm/udl: Unregister device before cleaning up on disconnect
* ab390ab81241 drm/tegra: Fix a possible null pointer dereference
* c4baefcea942 drm/tegra: Assign plane type before registration
* 8488c952e776 HID: wacom: fix kobject reference count leak
* 60ce381b61c6 HID: wacom: fix memory leak on sysfs attribute creation failure
* fead8ecfa2a9 HID: wacom: fix memory leak on kobject creation failure
* 6d8f84794130 btrfs: update superblock's device bytes_used when dropping chunk
* 471590782c87 dm-raid: fix variable in journal device check
* f084a3e31bbb Bluetooth: L2CAP: Fix L2CAP MTU negotiation
* 331a3a116ff8 dt-bindings: serial: 8250: Make clocks and clock-frequency exclusive
* 4bb1bb438134 atm: Release atm_dev_mutex after removing procfs in atm_dev_deregister().
* ddc7b7b857f9 net: enetc: Correct endianness handling in _enetc_rd_reg64
* e9da8640820c um: ubd: Add missing error check in start_io_thread()
* 162ac8836c57 vsock/uapi: fix linux/vm_sockets.h userspace compilation errors
* 48939325f88b wifi: mac80211: fix beacon interval calculation overflow
* d6c6216a7e85 libbpf: Fix null pointer dereference in btf_dump__free on allocation failure
* 451b9495fed2 attach_recursive_mnt(): do not lock the covering tree when sliding something under it
* 2dc1c3edf67a ALSA: usb-audio: Fix out-of-bounds read in snd_usb_get_audioformat_uac3()
* 41f6420ee845 atm: clip: prevent NULL deref in clip_push()
* 8bc5879c038f i2c: robotfuzz-osif: disable zero-length read messages
* 4e093e67e5a9 i2c: tiny-usb: disable zero-length read messages
* 2254d038dab9 net_sched: sch_sfq: reject invalid perturb period
* 85d6dde17001 PCI: cadence-ep: Correct PBA offset in .set_msix() callback
* 3d19fa73b130 uio_hv_generic: Align ring size to system page
* 6d748a084cdf uio_hv_generic: Query the ringbuffer size for device
* ab839c2c2ccb Drivers: hv: vmbus: Add utility function for querying ring size
* c111cd1835c0 Drivers: hv: Rename 'alloced' to 'allocated'
* 9eeb2d81f1ab Drivers: hv: vmbus: Fix duplicate CPU assignments within a device
* 4564cc9afe7d uio: uio_hv_generic: use devm_kzalloc() for private data alloc
* bf7eff5e3a36 RDMA/iwcm: Fix use-after-free of work objects after cm_id destruction
* 904b69380690 RDMA/core: Use refcount_t instead of atomic_t on refcount of iwcm_id_private
* b189e5c23711 f2fs: don't over-report free space or inodes in statvfs
* ffb241bb31bd can: tcan4x5x: fix power regulator retrieval during probe
* bd3cb55817e6 media: omap3isp: use sgtable-based scatterlist wrappers
* a4259e72363e jfs: validate AG parameters in dbMount() to prevent crashes
* 7448fd8d9816 fs/jfs: consolidate sanity checking in dbMount
* eb14934a14ed usb: typec: tcpm/tcpci_maxim: Fix bounds check in process_rx()
* 3a4097f449af usb: typec: tcpci_maxim: add terminating newlines to logging
* 1b33e13d9bc1 usb: typec: tcpci_maxim: remove redundant assignment
* ee35c221ce92 usb: typec: tcpci_maxim: Fix uninitialized return variable
* 468aec888f83 VMCI: fix race between vmci_host_setup_notify and vmci_ctx_unset_notify
* d4198f67e755 VMCI: check context->notify_page after call to get_user_pages_fast() to avoid GPF
* 0eacf8aa021a ovl: Check for NULL d_inode() in ovl_dentry_upper()
* 9da0ec75612b ceph: fix possible integer overflow in ceph_zero_objects()
* 279beb115844 ALSA: hda: Add new pci id for AMD GPU display HD audio controller
* 990b6b3c85cd ALSA: hda: Ignore unsol events for cards being shut down
* e3fb6c2c3939 usb: typec: displayport: Receive DP Status Update NAK request exit dp altmode
* 846f10d8cf42 usb: cdc-wdm: avoid setting WDM_READ for ZLP-s
* 65c364ced26d usb: Add checks for snprintf() calls in usb_alloc_dev()
* 27772cbbcd86 usb: common: usb-conn-gpio: use a unique name for usb connector device
* 603a83e5fee3 usb: potential integer overflow in usbg_make_tpg()
* f52313b5b119 um: Add cmpxchg8b_emu and checksum functions to asm-prototypes.h
* 139fce940fec iio: pressure: zpa2326: Use aligned_s64 for the timestamp
* d54681938b77 bcache: fix NULL pointer in cache_set_flush()
* f768d19d42a6 md/md-bitmap: fix dm-raid max_write_behind setting
* 761dc6dd5560 dmaengine: xilinx_dma: Set dma_device directions
* 3f895098bd78 hwmon: (pmbus/max34440) Fix support for max34451
* c05e354347f7 leds: multicolor: Fix intensity setting while SW blinking
* bd0a4fee2585 mfd: max14577: Fix wakeup source leaks on device unbind
* e693e083aafe mailbox: Not protect module_put with spin_lock_irqsave
* 45e48f361a1d NFSv4.2: fix listxattr to return selinux security label
* 51efea7efa24 cifs: Fix cifs_query_path_info() for Windows NT servers

Change-Id: I24504755cb73cbe2ee0ec5f3b4679369c5057e09
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>