ANDROID: zram: Fix build break with zram_can_store_pages w/o CONFIG_ZRAM_WRITEBACK
The zram_can_store_page() function was added in commit
160a4092db67 ("ANDROID: zram: Add ZRAM_ANDROID_IOC_PROCESS_PREFETCH
ioctl") but only used in logic enabled w/ CONFIG_ZRAM_WRITEBACK.

This causes build errors when CONFIG_ZRAM_WRITEBACK is disabled:
  error: unused function 'zram_can_store_page' [-Werror,-Wunused-function]

So move the function in CONFIG_ZRAM_WRITEBACK as well.

Fixes: 160a4092db67 ("ANDROID: zram: Add ZRAM_ANDROID_IOC_PROCESS_PREFETCH ioctl")
Bug: 495288884
Bug: 495197959
Change-Id: If6e1bcce9ea31811367e3b481a886ffbfca3fda4
Signed-off-by: Richard Chang <richardycc@google.com>
(cherry picked from commit d671506859f7d94850bd3c4d112169e45942ed98)