Merge 6.6.90 into android15-6.6-lts
GKI (arm64) relevant 42 out of 129 changes, affecting 79 files +697/-309
  f73ecbfa78ce ALSA: usb-audio: Add retry on -EPROTO from usb_set_interface() [1 file, +7/-0]
  3ac18e0a94c1 ALSA: usb-audio: Add second USB ID for Jabra Evolve 65 headset [1 file, +2/-1]
  94808275aa6c drm/fdinfo: Protect against driver unbind [1 file, +6/-0]
  3821cae9bd5a arm64: errata: Add missing sentinels to Spectre-BHB MIDR arrays [1 file, +2/-0]
  c0fabecd6510 mm/memblock: pass size instead of end to memblock_set_node() [1 file, +1/-1]
  4d1a2d136356 mm/memblock: repeat setting reserved region nid if array is doubled [1 file, +10/-0]
  8daa71c694b3 tracing: Do not take trace_event_sem in print_event_fields() [1 file, +2/-2]
  c8c83052283b dm-bufio: don't schedule in atomic context [1 file, +8/-1]
  64e95bb37916 dm: always update the array size in realloc_argv on success [1 file, +3/-2]
  cbd54987db25 cpufreq: Avoid using inconsistent policy->min and policy->max [1 file, +25/-7]
  25687fd19633 cpufreq: Fix setting policy limits when frequency tables are used [4 files, +73/-41]
  056ebbddb8fa tracing: Fix oob write in trace_seq_to_buffer() [1 file, +3/-2]
  f0b56f1d2fcc bpf: add find_containing_subprog() utility function [1 file, +24/-4]
  3d496a1eaaec bpf: refactor bpf_helper_changes_pkt_data to use helper number [4 files, +31/-38]
  79751e9227a5 bpf: track changes_pkt_data property for global functions [2 files, +32/-1]
  7197fc4acdf2 bpf: check changes_pkt_data property for extension programs [2 files, +13/-4]
  f1692ee23dca bpf: consider that tail calls invalidate packet pointers [1 file, +2/-0]
  3a467d938da2 bpf: fix null dereference when computing changes_pkt_data of prog w/o subprogs [1 file, +5/-2]
  a6dbcf69d4c4 iommu: Handle race with default domain setup [1 file, +18/-0]
  8890eeae5c82 ASoC: soc-pcm: Fix hw_params() and DAPM widget sequence [1 file, +4/-1]
  8dde02229b3c net: Rename mono_delivery_time to tstamp_type for scalabilty [17 files, +78/-51]
  8c7bfb6198a7 Bluetooth: L2CAP: copy RX timestamp to new fragments [1 file, +3/-0]
  012a413b28e1 nvme-pci: fix queue unquiesce check on slot_reset [1 file, +1/-1]
  e0272844995a net: ipv6: fix UDPv6 GSO segmentation with NAT [1 file, +60/-1]
  85484bc61138 ASoC: soc-core: Stop using of_property_read_bool() for non-boolean properties [1 file, +13/-19]
  bbbf5e0f8707 sch_htb: make htb_qlen_notify() idempotent [1 file, +2/-0]
  2fbf6c9695ad firmware: arm_scmi: Balance device refcount when destroying devices [1 file, +3/-0]
  6299fb6190fe xhci: Set DESI bits in ERDP register correctly [3 files, +13/-15]
  f377434945f5 xhci: Use more than one Event Ring segment [2 files, +10/-5]
  3f6e8ad65b1e xhci: Clean up stale comment on ERST_SIZE macro [1 file, +1/-6]
  ff0a51339a3b xhci: split free interrupter into separate remove and free parts [1 file, +21/-11]
  bcd191d7bab2 xhci: add support to allocate several interrupters [5 files, +137/-32]
  3733697cb7dd xhci: Add helper to set an interrupters interrupt moderation interval [1 file, +18/-7]
  cc64775afb27 usb: xhci: check if 'requested segments' exceeds ERST capacity [2 files, +14/-14]
  ebb7195dac40 xhci: support setting interrupt moderation IMOD for secondary interrupters [3 files, +13/-4]
  baa3ebbad80f xhci: Limit time spent with xHC interrupts disabled during bus resume [3 files, +20/-16]
  0ecbb45e30ab kernel: param: rename locate_module_kobject [1 file, +3/-3]
  ace531f2fea1 kernel: globalize lookup_or_create_module_kobject() [2 files, +3/-1]
  8f2451ebaf5b drivers: base: handle module_kobject creation [1 file, +5/-8]
  3efb29f6a78d usb: xhci: Check for xhci->interrupters being allocated in xhci_mem_clearup() [1 file, +1/-1]
  fe465003bb63 xhci: fix possible null pointer dereference at secondary interrupter removal [1 file, +6/-6]
  ed3248a40374 dm: fix copying after src array boundaries [1 file, +1/-1]

Changes in 6.6.90
	Revert "rndis_host: Flag RNDIS modems as WWAN devices"
	ALSA: usb-audio: Add retry on -EPROTO from usb_set_interface()
	ALSA: usb-audio: Add second USB ID for Jabra Evolve 65 headset
	btrfs: fix COW handling in run_delalloc_nocow()
	drm/fdinfo: Protect against driver unbind
	drm/nouveau: Fix WARN_ON in nouveau_fence_context_kill()
	EDAC/altera: Test the correct error reg offset
	EDAC/altera: Set DDR and SDMMC interrupt mask before registration
	i2c: imx-lpi2c: Fix clock count when probe defers
	arm64: errata: Add missing sentinels to Spectre-BHB MIDR arrays
	parisc: Fix double SIGFPE crash
	perf/x86/intel: KVM: Mask PEBS_ENABLE loaded for guest with vCPU's value.
	amd-xgbe: Fix to ensure dependent features are toggled with RX checksum offload
	irqchip/qcom-mpm: Prevent crash when trying to handle non-wake GPIOs
	mm/memblock: pass size instead of end to memblock_set_node()
	mm/memblock: repeat setting reserved region nid if array is doubled
	mmc: renesas_sdhi: Fix error handling in renesas_sdhi_probe
	spi: tegra114: Don't fail set_cs_timing when delays are zero
	tracing: Do not take trace_event_sem in print_event_fields()
	wifi: brcm80211: fmac: Add error handling for brcmf_usb_dl_writeimage()
	dm-bufio: don't schedule in atomic context
	dm-integrity: fix a warning on invalid table line
	dm: always update the array size in realloc_argv on success
	iommu/amd: Fix potential buffer overflow in parse_ivrs_acpihid
	iommu/vt-d: Apply quirk_iommu_igfx for 8086:0044 (QM57/QS57)
	platform/x86/amd: pmc: Require at least 2.5 seconds between HW sleep cycles
	platform/x86/intel-uncore-freq: Fix missing uncore sysfs during CPU hotplug
	ksmbd: fix use-after-free in kerberos authentication
	smb: client: fix zero length for mkdir POSIX create context
	cpufreq: Avoid using inconsistent policy->min and policy->max
	cpufreq: Fix setting policy limits when frequency tables are used
	tracing: Fix oob write in trace_seq_to_buffer()
	bpf: add find_containing_subprog() utility function
	bpf: refactor bpf_helper_changes_pkt_data to use helper number
	bpf: track changes_pkt_data property for global functions
	selftests/bpf: test for changing packet data from global functions
	bpf: check changes_pkt_data property for extension programs
	selftests/bpf: freplace tests for tracking of changes_packet_data
	bpf: consider that tail calls invalidate packet pointers
	selftests/bpf: validate that tail call invalidates packet pointers
	bpf: fix null dereference when computing changes_pkt_data of prog w/o subprogs
	selftests/bpf: extend changes_pkt_data with cases w/o subprograms
	Revert "PCI: imx6: Skip controller_id generation logic for i.MX7D"
	PCI: imx6: Skip controller_id generation logic for i.MX7D
	KVM: x86: Load DR6 with guest value only before entering .vcpu_run() loop
	iommu: Handle race with default domain setup
	ASoC: soc-pcm: Fix hw_params() and DAPM widget sequence
	book3s64/radix : Align section vmemmap start address to PAGE_SIZE
	powerpc/boot: Check for ld-option support
	drm/i915/pxp: fix undefined reference to `intel_pxp_gsccs_is_ready_for_sessions'
	wifi: plfxlc: Remove erroneous assert in plfxlc_mac_release
	powerpc/boot: Fix dash warning
	vxlan: vnifilter: Fix unlocked deletion of default FDB entry
	net/mlx5: E-Switch, Initialize MAC Address for Default GID
	net/mlx5: E-switch, Fix error handling for enabling roce
	Bluetooth: btusb: avoid NULL pointer dereference in skb_dequeue()
	net: Rename mono_delivery_time to tstamp_type for scalabilty
	Bluetooth: L2CAP: copy RX timestamp to new fragments
	net: mscc: ocelot: treat 802.1ad tagged traffic as 802.1Q-untagged
	net: mscc: ocelot: delete PVID VLAN when readding it as non-PVID
	net: ethernet: mtk-star-emac: fix spinlock recursion issues on rx/tx poll
	net: ethernet: mtk-star-emac: rearm interrupts in rx_poll only when advised
	pds_core: check health in devcmd wait
	pds_core: delete VF dev on reset
	pds_core: make pdsc_auxbus_dev_del() void
	pds_core: specify auxiliary_device to be created
	pds_core: remove write-after-free of client_id
	net_sched: drr: Fix double list add in class with netem as child qdisc
	net_sched: hfsc: Fix a UAF vulnerability in class with netem as child qdisc
	net_sched: ets: Fix double list add in class with netem as child qdisc
	net_sched: qfq: Fix double list add in class with netem as child qdisc
	ice: Check VF VSI Pointer Value in ice_vc_add_fdir_fltr()
	ALSA: ump: Fix buffer overflow at UMP SysEx message conversion
	nvme-pci: fix queue unquiesce check on slot_reset
	net: dlink: Correct endianness handling of led_mode
	net: mdio: mux-meson-gxl: set reversed bit when using internal phy
	igc: fix lock order in igc_ptp_reset
	net: ethernet: mtk_eth_soc: fix SER panic with 4GB+ RAM
	net: dsa: felix: fix broken taprio gate states after clock jump
	net: ipv6: fix UDPv6 GSO segmentation with NAT
	bnxt_en: Fix coredump logic to free allocated buffer
	bnxt_en: Fix out-of-bound memcpy() during ethtool -w
	bnxt_en: Fix ethtool -d byte order for 32-bit values
	nvme-tcp: fix premature queue removal and I/O failover
	net: lan743x: Fix memleak issue when GSO enabled
	net: fec: ERR007885 Workaround for conventional TX
	octeon_ep: Fix host hang issue during device reboot
	net: hns3: store rx VLAN tag offload state for VF
	net: hns3: fix an interrupt residual problem
	net: hns3: fixed debugfs tm_qset size
	net: hns3: defer calling ptp_clock_register()
	net: vertexcom: mse102x: Fix possible stuck of SPI interrupt
	net: vertexcom: mse102x: Fix LEN_MASK
	net: vertexcom: mse102x: Add range check for CMD_RTS
	net: vertexcom: mse102x: Fix RX error handling
	ASoC: Use of_property_read_bool()
	ASoC: soc-core: Stop using of_property_read_bool() for non-boolean properties
	riscv: Pass patch_text() the length in bytes
	sch_htb: make htb_qlen_notify() idempotent
	sch_drr: make drr_qlen_notify() idempotent
	sch_hfsc: make hfsc_qlen_notify() idempotent
	sch_qfq: make qfq_qlen_notify() idempotent
	sch_ets: make est_qlen_notify() idempotent
	firmware: arm_scmi: Balance device refcount when destroying devices
	firmware: arm_ffa: Skip Rx buffer ownership release if not acquired
	ARM: dts: opos6ul: add ksz8081 phy properties
	arm64: dts: st: Adjust interrupt-controller for stm32mp25 SoCs
	arm64: dts: st: Use 128kB size for aliased GIC400 register access on stm32mp25 SoCs
	Revert "drm/meson: vclk: fix calculation of 59.94 fractional rates"
	xhci: Set DESI bits in ERDP register correctly
	xhci: Use more than one Event Ring segment
	xhci: Clean up stale comment on ERST_SIZE macro
	xhci: split free interrupter into separate remove and free parts
	xhci: add support to allocate several interrupters
	xhci: Add helper to set an interrupters interrupt moderation interval
	usb: xhci: check if 'requested segments' exceeds ERST capacity
	xhci: support setting interrupt moderation IMOD for secondary interrupters
	xhci: Limit time spent with xHC interrupts disabled during bus resume
	kernel: param: rename locate_module_kobject
	kernel: globalize lookup_or_create_module_kobject()
	drivers: base: handle module_kobject creation
	iommu/arm-smmu-v3: Use the new rb tree helpers
	iommu/arm-smmu-v3: Fix iommu_device_probe bug due to duplicated stream ids
	drm/amd/display: Add scoped mutexes for amdgpu_dm_dhcp
	drm/amd/display: Fix slab-use-after-free in hdcp
	usb: xhci: Check for xhci->interrupters being allocated in xhci_mem_clearup()
	xhci: fix possible null pointer dereference at secondary interrupter removal
	dm: fix copying after src array boundaries
	Linux 6.6.90

Change-Id: I6eb816adae9239ed0aaaaf8519c953c4e5bed297
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>