ANDROID: reduce content in build.config.db845c.
All configs except DTC_FLAGS is moved to BUILD.bazel.

As a side effect of setting kernel_build(defconfig), Kleaf enforces that
the final .config has all values required by db845c_gki.fragment. If
that causes build errors like the following in the future, we should
either fix db845c_gki.fragment, or set
kernel_build(check_defconfig = "disabled").

    ERROR: CONFIG_USB_ROLE_SWITCH: actual 'y', expected 'm' from common/arch/arm64/configs/db845c_gki.fragment

Bug: 236012223
Change-Id: Id5b3f264e690176ac59846d32e0d6c62600a8190
Signed-off-by: HONG Yifan <elsk@google.com>