gbl: require libavb ops for prod builds
Modifies the libavb ops implementation to only fallback to default
behavior on dev builds. Prod builds will error out instead.

This CL also changes some fallback behavior:

1. validate_vbmeta_public_key: CustomKey -> Invalid

Invalid seems more correct here, since we don't have any key we're
comparing against at all. This still allows booting on dev boards, since
we're running unlocked, but more correctly indicates that no signing was
verified.

2. persistent named values: no-op -> NoSuchValue

libavb has special handling for the NoSuchValue return code, which
should still allow it to boot in unlocked mode, and more correctly
represents the state of the device.

Cuttlefish prod boot log:

```
Android loading v3 or higher
Panics! panicked at external/gbl/efi/app/main.rs:54:21:
called `Result::unwrap()` on an `Err` value: AvbIoError(NotImplemented)
```

Cuttlefish dev boot log:

```
Android loading v3 or higher
AVB read device unlocked unimplemented, defaulting to Ok(true)
AVB validate vbmeta key unimplemented, defaulting to Ok(Invalid)
avb_slot_verify.c:915: ERROR: vbmeta_a: Public key used to sign data rejected.
AVB read rollback index unimplemented, defaulting to Ok(0)
AVB read rollback index unimplemented, defaulting to Ok(0)
AVB read rollback index unimplemented, defaulting to Ok(0)
AVB read rollback index unimplemented, defaulting to Ok(0)
AVB read rollback index unimplemented, defaulting to Ok(0)
AVB read rollback index unimplemented, defaulting to Ok(0)
AVB read device unlocked unimplemented, defaulting to Ok(true)
AVB verification failed with Public key rejected or data not signed. Device is unlocked: true. Color: orange. Continue current boot attempt.
```

Bug: b/408283572
Change-Id: I7e3a9947eff6828ca123dbada86eeeff8af068b1