kleaf: arm64_16k: rename CONFIG_PAGE_BLOCK_ORDER
The config was renamed in commit [1] to CONFIG_PAGE_BLOCK_MAX_ORDER and
needs to be updated here, to fix the following build issue:

  ERROR: CONFIG_PAGE_BLOCK_ORDER: actual '', expected '7' from build/kernel/kleaf/impl/defconfig/arm64_16k_defconfig

Cc: Juan Yescas <jyescas@google.com>
Link: https://git.kernel.org/torvalds/c/3800d5525097 [1]
Change-Id: Ie1574c241745b1c5424bbeebff48539272ec76cb
Signed-off-by: Carlos Llamas <cmllamas@google.com>