ANDROID: KVM: arm64: Fix KernelCI build issue from __pkvm_teardown_tracing
__pkvm_teardown_tracing was recently modified to return an int, but its
placeholder function was not updated to match, resulting in the
following kernelci build errors:

with clang-21:
arch/arm64/kvm/hyp/nvhe/hyp-main.c:1570:24: error: assigning to '__u64' (aka 'unsigned long long') from incompatible type 'void'
 1570 |         cpu_reg(host_ctxt, 1) = __pkvm_teardown_tracing();
      |                               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[6]: *** [arch/arm64/kvm/hyp/nvhe/Makefile.nvhe:35: arch/arm64/kvm/hyp/nvhe/hyp-main.nvhe.o] Error 1
make[5]: *** [scripts/Makefile.build:511: arch/arm64/kvm/hyp/nvhe] Error 2
make[4]: *** [scripts/Makefile.build:511: arch/arm64/kvm/hyp] Error 2
make[4]: *** Waiting for unfinished jobs....
  CC      kernel/module/sysfs.o
  CC      lib/logic_pio.o
make[3]: *** [scripts/Makefile.build:511: arch/arm64/kvm] Error 2

with gcc-14:
arch/arm64/kvm/hyp/nvhe/hyp-main.c: In function ‘handle___pkvm_teardown_tracing’:
arch/arm64/kvm/hyp/nvhe/hyp-main.c:1570:31: error: void value not ignored as it ought to be
 1570 |         cpu_reg(host_ctxt, 1) = __pkvm_teardown_tracing();
      |                               ^
make[6]: *** [arch/arm64/kvm/hyp/nvhe/Makefile.nvhe:35: arch/arm64/kvm/hyp/nvhe/hyp-main.nvhe.o] Error 1
make[5]: *** [scripts/Makefile.build:511: arch/arm64/kvm/hyp/nvhe] Error 2
make[4]: *** [scripts/Makefile.build:511: arch/arm64/kvm/hyp] Error 2
make[3]: *** [scripts/Makefile.build:511: arch/arm64/kvm] Error 2
make[2]: *** [scripts/Makefile.build:511: arch/arm64] Error 2

Make the function signatures consistent.

Fixes: 416566c3ecff ("ANDROID: KVM: arm64: Return an error from __pkvm_teardown_tracing")
Reported-by: kernelci.org bot <bot@kernelci.org>
Closes: https://d.kernelci.org/i/maestro:e2e461b343ebd1255c85313b05f7b5c1e886d6c8
Closes: https://d.kernelci.org/i/maestro:b2e308e2b7d9d3f9689fe09d7e9f81583f7a568e
Change-Id: Ic2d7c775cd296014acf5efeef79dae6eeeb534e6
Signed-off-by: Tiffany Yang <ynaffit@google.com>