Reapply "mei: rework Kconfig dependencies"
This reverts commit b8ed6629a340b94a1aaea0215b2182fc1ce0837b.

Resolves trivial merge conflicts in:
	drivers/misc/mei/Kconfig
	drivers/misc/mei/hdcp/Kconfig
	drivers/misc/mei/pxp/Kconfig

The lack of this commit causes an arm_allmodconfig build failure as
INTEL_MEI_ME is only expected to be selected for X86.

  WARNING: unmet direct dependencies detected for INTEL_MEI_ME
    Depends on [n]: X86 && PCI [=y]
    Selected by [m]:
    - INTEL_MEI_HDCP [=m] && (DRM_I915 [=n] || DRM_XE [=m])
    - INTEL_MEI_PXP [=m] && (DRM_I915 [=n] || DRM_XE [=m])

  drivers/gpu/drm/xe/xe_gen_wa_oob.c:130:5:
  error: incompatible integer to pointer conversion assigning to
         'const char *' from 'int' [-Wint-conversion]
    130 |         fn = basename(fn);
        |            ^ ~~~~~~~~~~~~

Change-Id: Ie9e307a4ae9ca88d5bcc4834da1bc1f7608d9699
Signed-off-by: Carlos Llamas <cmllamas@google.com>