ANDROID: sched: remove ifdef around __migrate_task
Commit cac5cefbade9 ("sched/smp: Make SMP unconditional") removed if
guards that used to be present around __migrate_task. We expose this
function to Android vendors, so KCI is giving the following build errors:

kernel/sched/core.c:2597:12: error: no previous prototype for ‘__migrate_task’ [-Werror=missing-prototypes]
 2597 | struct rq *__migrate_task(struct rq *rq, struct rq_flags *rf,
      |            ^~~~~~~~~~~~~~

Remove the CONFIG_SMP if guards around the function prototype.

Change-Id: I849517a2cfe8a6883c6844fa77a905eb1a86c0f0
Fixes: 60d27463094b ("ANDROID: sched: allow access to critical common code for CPU Pause")
Signed-off-by: Tiffany Yang <ynaffit@google.com>