FROMLIST: objtool: HAVE_XXHASH test uses HOSTCFLAGS.
Previously, HAVE_XXHASH is tested by invoking HOSTCC without HOSTCFLAGS.

Consider the following scenario:

- The host machine has libxxhash installed
- We build the kernel with HOSTCFLAGS containing a --sysroot that does
  not have xxhash.h (for hermetic builds)

In this case, HAVE_XXHASH is set to y, but when it builds objtool with
HOSTCFLAGS, because the --sysroot does not contain xxhash.h, the
following error is raised:

<...>/common/tools/objtool/include/objtool/checksum_types.h:12:10: fatal error: 'xxhash.h' file not found
   12 | #include <xxhash.h>
      |          ^~~~~~~~~~

To resolve the error, we test HAVE_XXHASH by invoking HOSTCC with
HOSTCFLAGS.

Link: https://lore.kernel.org/lkml/20260303010340.306164-1-elsk@google.com/
Bug: 488332737
Change-Id: I406c3b406514e5069f9b2d8c2582389a4ca043ba
Signed-off-by: HONG Yifan <elsk@google.com>