ANDROID: dm-bow: fix -Wmissing-prototypes errors
Add missing 'static' keyword to several functions. This resolves build
issues after enabling -Wmissing-prototypes such as the following:

  common/drivers/md/dm-bow.c:98:10: error: no previous prototype for function 'range_top' [-Werror,-Wmissing-prototypes]
     98 | sector_t range_top(struct bow_range *br)
        |          ^

Cc: Paul Lawrence <paullawrence@google.com>
Fixes: 0ce3eb37e9ea ("ANDROID: dm-bow: Add dm-bow feature")
Change-Id: I66a3272b3a9a9b44ff687ac416722cad04fea651
Signed-off-by: Carlos Llamas <cmllamas@google.com>