ANDROID: GKI: x86: Update ABI
Update ABI to fix broken x86 build:

ERROR: ABI DIFFERENCES HAVE BEEN DETECTED!
ERROR: Report summary:

function symbol 'int snd_pcm_lib_default_mmap(struct snd_pcm_substream*, struct vm_area_struct*)' changed
  CRC changed from 0x4d0224e6 to 0x20838777

function symbol 'int snd_pcm_stop(struct snd_pcm_substream*, snd_pcm_state_t)' changed
  CRC changed from 0xd77ebfb0 to 0x817333eb

function symbol 'int snd_pcm_stop_xrun(struct snd_pcm_substream*)' changed
  CRC changed from 0x1212d5e0 to 0x5efdf70f

... 3 omitted; 6 symbols have only CRC changes

Bug: none
Test: tools/bazel run //common:kernel_x86_64_abi_update
Change-Id: I09554bc447bc4ee911917080a4d8b7e11e6a4768
Signed-off-by: Dmytro Maluka <dmaluka@google.com>