Revert "ANDROID: kleaf: select uapi headers for parse_vdso"
This reverts commit af99cf46e2c7f4fbed3ad527d236914e207500cb.

It is no longer needed since commit 5abfa0c4da3b ("Revert "selftests:
vDSO: parse_vdso: Use UAPI headers instead of libc headers"") has
switched back to using libc headers. Reverting this commit fixes the
duplicate definitions with the UAPI headers:

  tools/testing/selftests/vDSO/parse_vdso.c:22:
  usr/include/elf.h:124:3: error: typedef redefinition with different types ('struct Elf32_Verdef' vs 'struct Elf32_Verdef')
    124 | } Elf32_Verdef;
        |   ^
  include/uapi/linux/elf.h:593:3: note: previous definition is here
    593 | } Elf32_Verdef;
        |   ^

Change-Id: I35750e94b9718d86caa87391ba482f75f06fb339
Signed-off-by: Carlos Llamas <cmllamas@google.com>