kleaf: workspace_status_stamp.py: Fix pathlib.path error
Currently, there are two places where "pathlib.path" is used instead
of the correct "pathlib.Path". This causes the following error when
building with --ignore_missing_projects:

AttributeError: module 'pathlib' has no attribute 'path'. Did you mean: 'Path'?

Fix this by changing "pathlib.path" to "pathlib.Path".

Bug: 306026132
Change-Id: I8ecdec3b48d7438a3a953944f629b462a7c88536
Signed-off-by: John Moon <quic_johmoo@quicinc.com>
(cherry picked from commit 224cf84e94caf3db491139ce2dac462d97a833e3)