ANDROID: x86: gki_defconfig: Re-align with saveconfig's succinct result
Pre-submit has the following to say:

  ERROR: savedefconfig does not match common/arch/x86/configs/gki_defconfig

Fixes: e6bcfdd75d53 ("x86/microcode: Hide the config knob")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: Ib99d85ac52cec3b62176728c2dedbc0d3d69a3bd