ANDROID: sched: Export set_task_cpu inside of ifdef
Fix the following kernelci build error on non-CONFIG_SMP systems:

ERROR: modpost: vmlinux: local symbol 'set_task_cpu' was exported

Fixes: a085424328b2 ("ANDROID: Export some scheduler APIs for vendor modules")
Change-Id: Iba0c7f1c62fe0b2e4c386ad9adfa0ded61fd3733
Signed-off-by: Tiffany Yang <ynaffit@google.com>