ANDROID: Delete build.config.amlogic.
All build configs can be represented in BUILD.bazel.

As a side effect of setting kernel_build(defconfig), Kleaf enforces that
the final .config has all values required by amlogic_gki.fragment. If
that causes build errors like the following in the future, we should
either fix amlogic_gki.fragment, or set
kernel_build(check_defconfig = "disabled").

    ERROR: CONFIG_BRCMUTIL: actual '', expected 'm' from common/arch/arm64/configs/amlogic_gki.fragment

Bug: 236012223
Change-Id: I7ef7a27159447e3d9d2609ee7586a67e2c685459
Signed-off-by: HONG Yifan <elsk@google.com>