Autoupdate of 4 submodules
*gs/google-modules/aoc updated to b662ca2556d395899148487fa08ff0760b306c1f
aoc/alsa: Fix undefined type specifiers

alsa/aoc_alsa_hw.c:25:8: error: type specifier missing, defaults to 'int'
[-Werror,-Wimplicit-int]
static aoc_audio_sink[] = {
~~~~~~ ^
alsa/aoc_alsa_hw.c:125:8: error: type specifier missing, defaults to 'int'
[-Werror,-Wimplicit-int]
static aoc_audio_stream_type[] = {
~~~~~~ ^
2 errors generated.

Bug: 228686072
Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Ie3c294f06a30cbea27c4712bf5ac96883db959e9

*gs/google-modules/bms updated to d6c59933b6b444a5ece6828bee127fe758f11c5c
pca9468_charger: Fix implicit type specifier errors

pca9468_charger.c:1624:8: error: type specifier missing, defaults to 'int'
[-Werror,-Wimplicit-int]
        const ibat_limit = (pca9468->cc_max * FCC_POWER_INCREASE_THRESHOLD) / 100;
        ~~~~~ ^
1 error generated.

Bug: 228686072
Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: I0594606706ac5961ec76a77a05d1cf0549f456e1

*gs/google-modules/display updated to cbaccfeb6649297060f6af006263fa46b91102c1
drm: samsung: decon: Fix implicit type specifier error

samsung/exynos_drm_decon.c:1100:8: error: type specifier missing, defaults to
'int' [-Werror,-Wimplicit-int]
        const frame_time_ms = DIV_ROUND_UP(MSEC_PER_SEC, fps ? : 60);
        ~~~~~ ^
1 error generated.

Bug: 228686072
Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: I8b13fb3cef725c5c9f28cc7ae1c6debddd223c1c

*gs/google-modules/soc-modules updated to 0a5366d6dcb066f70f815ba057621ed195a9ddba
usb: typec: tcpci_fusb307: fix missing type specifier

drivers/usb/typec/tcpm/tcpci_fusb307.c:212:8: error: type specifier missing,
defaults to 'int' [-Werror,-Wimplicit-int]
static enable_load_switch(struct fusb307b_plat *chip)
~~~~~~ ^
1 error generated.

Bug: 228686072
Signed-off-by: Will McVicker <willmcvicker@google.com>
Change-Id: Iddf0d68344f3001855ed6132a4da26cf124289fc