Remove unused rules_rust references
Without this change, trying to use 1.78.0 in android-mainline fails with
the following error:

ERROR: error loading package 'prebuilts/rust/linux-x86/1.78.0': Unable to find package for @@[unknown repo 'rules_rust' requested from @@]//rust:defs.bzl: The repository '@@[unknown repo 'rules_rust' requested from @@]' could not be resolved: No repository visible as '@rules_rust' from main repository.
ERROR: /usr/local/google/home/aliceryhl/android-mainline/common/BUILD.bazel:94:22: every rule of type kernel_env implicitly depends upon the target '//prebuilts/rust/linux-x86/1.78.0:binaries', but this target could not be found because of: error loading package 'prebuilts/rust/linux-x86/1.78.0': Unable to find package for @@[unknown repo 'rules_rust' requested from @@]//rust:defs.bzl: The repository '@@[unknown repo 'rules_rust' requested from @@]' could not be resolved: No repository visible as '@rules_rust' from main repository.
ERROR: Analysis of target '//common:kernel_x86_64_dist' failed; build aborted: Analysis failed

This change fixes it using the same approach as aosp/3106861 from the
1.73.0c prebuilt.

Test: Compile android-mainline + Rust with and without this change
Change-Id: I985ab4050573d9acf140a97b01001d6651de9408