ANDROID: db845c fix defconfig to be like .config
Some values in defconfig are set but isn't present in the final .config.
So we change them to be the value in .config.

Fixes the following errors when setting kernel_build(defconfig):

    ERROR: CONFIG_USB_ROLE_SWITCH: actual 'y', expected 'm' from common/arch/arm64/configs/db845c_gki.fragment
    ERROR: CONFIG_QCOM_GLINK_SSR: actual '', expected 'm' from common/arch/arm64/configs/db845c_gki.fragment
    ERROR: CONFIG_MFD_QCOM_QCA639X: actual '', expected 'm' from common/arch/arm64/configs/db845c_gki.fragment
    ERROR: CONFIG_SM_DISPCC_8650: actual '', expected 'm' from common/arch/arm64/configs/db845c_gki.fragment

Bug: 236012223
Test: check that .config does not change before and after this CL.
Change-Id: Icbd7b6181a460c81ce6888a5d77d6cee00edb968
Signed-off-by: HONG Yifan <elsk@google.com>