Autoupdate of 18 submodules
*common updated to a4c7102a3ea3bde5d061500e7c0c52e4db0e4b1a
Reapply "kbuild: remove EXTRA_*FLAGS support"

This reverts commit 695728b4bd38592f0876d915d227b47139275aee.

Android has carried this revert for too long. The OOT drivers should
instead be updated to reflect the EXTRA_CFLAGS and similar removal.
There are other options such as KCFLAGS, CFLAGS_MODULE and ccflags-y
that should serve as a replacement depending on the specifics.

Bug: 412122604
Change-Id: I8512b6c20113af6ed6bfcc527898cad6c6fc4864
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/amplifiers updated to 4165dd7e71f8ca25cc4705cb538dff8869c52a4a
treewide: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The drivers
here are converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: I837a6657d8e4ad48bacd1211cab06009db25722a
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/aoc updated to 4d366f5bfb65c508159eec8ef385fc5653273af8
treewide: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The drivers
here are converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: I1327b5bd17a1326e31da6b66800e7f8aa88172f7
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/bluetooth/broadcom updated to c9f9fcd70e9e15aaf3bb846c97096fad3c6fac70
nitrous: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: Ia315883cdeaa014d3224c9f86f351265923bf110
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/bms updated to 077f977969a1d50ca22fa034a5e5158513c24bfc
bms: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: Ib76c03a266c6e5ef49963473e10e8057775a3253
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/display updated to 82d75c3117f26f9bebb78a040ad435fa4cabb348
drm: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: I95dd4bf99d85be1af7efe4b24a4c1f84e0f992bf
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/edgetpu/abrolhos updated to 3634fe4232b74417df8f4b6fca28d3def4ae9df2
edgetpu: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: I3e7e9d56c8ce80d496bcf7b52d2759ab750cd421
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/gpu updated to 94b3df2222de22d0d869ecdeab2fb1dc53fb83ca
gpu: fix -Wunterminated-string-initialization issue

After enabling the dormant CFLAGS_MODULE for this driver the following
unterminated-string-initialization issue was exposed:

  borr_mali_kbase/platform/pixel/pixel_gpu_power.c:223:12: error: initializer-string for character array is too long, array size is 4 but initializer has size 5 (including the null terminating character); did you mean to use the 'nonstring' attribute? [-Werror,-Wunterminated-string-initialization]
  223 |                 .magic = "pprs",
      |                          ^~~~~~

Fix this by simply adding the __nonstring attribute as suggested by the
compiler error.

Change-Id: Ib17a064b2ee67370a23f9bc20494d77e99ecdc54
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/lwis updated to 839967336dc2d7388412b3c9fe8323c7eb01184e
lwis: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: I1fd53f0e38190d08c4084671a7d6e59b58599d55
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/nfc updated to 277843b0706e697873cb6ea56db95bf597194f16
nfc: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: I4ab976853663f26505adfa80b05bf748bd3c5c20
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/power/reset updated to db6733128d2087ea492600ab6eba365584531d24
power: reset: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: Iadfc492cef5ab219467f9df739f4c66eabd1a1c3
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/soc/gs updated to 59481ea60af8082eda39f21d207772a2deca7ad9
treewide: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. These drivers
here are converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: Id5e7bf7bc089497ee8a63744cc79b1aaa4744153
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/touch/common updated to 6bfec1deb3ca9ca01ed5d3e4fbcbfd32edc7c4ae
gti: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: I4fd6f4d2b8ca8c26ccf06e05d88a83c233bbfe36
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/touch/fts updated to 85b0e990eb140d7a90e0e8c51fe6ea9c23f18c7b
treewide: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]

Change-Id: Id7b964bfdacdb760282d28d5ac09401a3407fc1a
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/touch/sec updated to 688a2efeadfb370f8f6f954e5527bf9ff7dcab39
touch: sec: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: Ifc0d1a42e42eb43248af7093d227596ca507a0d1
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/trusty updated to 0bec1017cf3874ddcd9b2979f7d3274f42f52419
trusty: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: I08fac63ad50f5f831b8fd99eeaf74e5453ee134f
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/video/gchips updated to aab672a0297dde4836d55a71e4af9aa568d09e75
bigo: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: If557ae671f9f58db6a018d2919c14403fd587685
Signed-off-by: Carlos Llamas <cmllamas@google.com>

*private/google-modules/wlan/bcmdhd4389 updated to a4ab66ca5a6f69218dd842483190dfe4ea519774
bcmdhd4389: convert to CFLAGS_MODULE

Upstream has removed the support for EXTRA_CFLAGS in [1]. The driver
here is converted to use CFLAGS_MODULE as a direct replacement. No
functional changes expected from this patch.

Bug: 412122604
Link: https://git.kernel.org/torvalds/c/e966ad0edd00 [1]
Change-Id: Ib1846fc0303022d6d72f7e78327b47aa0cf42b77
Signed-off-by: Carlos Llamas <cmllamas@google.com>