ANDROID: incfs: drop private 'struct file_attr'
Upstream introduced a 'struct file_attr' definition in commit
be7efb2d20d6 ("fs: introduce file_getattr and file_setattr syscalls"),
which collides with incfs OOT private definition here:

  fs/incfs/data_mgmt.h:284:8: error: redefinition of 'file_attr'
    284 | struct file_attr {
        |        ^
  include/uapi/linux/fs.h:226:8: note: previous definition is here
    226 | struct file_attr {
        |        ^
  1 error generated

Fortunately, incfs private definition is no longer used since commit
d4d1163e5358 ("ANDROID: Incremental fs: Add INCFS_IOC_GET_BLOCK_COUNT"),
and it can be simply removed.

Cc: Paul Lawrence <paullawrence@google.com>
Fixes: d4d1163e5358 ("ANDROID: Incremental fs: Add INCFS_IOC_GET_BLOCK_COUNT")
Change-Id: I6243ba6b6b31f2c931829be7b81ffc74926fc77b
Signed-off-by: Carlos Llamas <cmllamas@google.com>