Autoupdate of 2 submodules
*build/kernel updated to 661d6f776a8c0dc15a3ec7c9decea3c739ef55ff
kleaf: Add support for building ditto suite

This introduces a new config `ditto` to build the ditto suite, it
requires a special configuration as it depends on two repos that are not
part of the standard checkout.

This add a new fake module for repos which don't include the
test/dittuosuite project, as it's not available in any registry.

Tested: tools/bazel build @dittosuite//:all --config=ditto
Tested: tools/bazel build //common:kernel_aarch64
Bug: 429971301
Change-Id: I30a6191a40cc8b3bb566e9c73ec194683081acdf

*test/dittosuite updated to 5829bd41d096ca8d2c0431c8e6c887de810f1f61
Fix build error when compiling as Kleaf dependency

* This fixes the following error:
  src/utils.cpp:29:17: \
    error: variable has incomplete type 'struct stat64'

Tested: bazel build :all
Tested: tools/bazel build @dittosuite//:all --config=ditto
Bug: 429971301
Change-Id: I0a14bfa66e7df638b078d3fc603359103e6e3632