ANDROID: dm-bow: Fix empty else blocks
drivers/md/dm-bow.c:1149:51: error: suggest braces around empty body
in an ‘else’ statement [-Werror=empty-body]
drivers/md/dm-bow.c:1142:51: error: suggest braces around empty body
in an ‘else’ statement [-Werror=empty-body]

Link to kernelci result:
https://linux.kernelci.org/build/android/branch/android-mainline/kernel/v6.11-rc6-6389-g1cf1608b4abd8/

Build log: https://storage.kernelci.org/android/android-mainline/v6.11-rc6-6389-g1cf1608b4abd8/x86_64/allmodconfig/gcc-12/logs/kernel.log

Bug: 366029436
Test: compiles
Change-Id: I685754e895ef1cdfd7ab1ae323b36b4ae310a45d
Signed-off-by: Paul Lawrence <paullawrence@google.com>
(cherry picked from commit a1704797eeb02837aa306bc5d9184978eed5cfa0)