kleaf: rust_toolchain: Set default_edition = 2021 on rust_toolchain
In preparation for the Bazel 9 upgrade, rules_rust is being updated
to 0.63.0. In rules_rust 0.63.0, rust_bindgen requires an edition
and falls back to rust_toolchain.default_edition when --rust-edition
is not explicitly set (see https://github.com/bazelbuild/rules_rust/pull/3432).

Setting default_edition = "2021" on Kleaf's rust_toolchain definitions
ensures bindgen receives a valid edition. This fixes the following
issue with rules_rust 0.63.0 / Bazel 9:

"""
error: invalid value '' for '--rust-edition <EDITION>': "" is not a valid Rust edition
"""

This change is backward-compatible with rules_rust 0.56.0.

Bug: 495395547
Test: tools/bazel test //build/kernel/kleaf/tests/rust_test:rust_test_unit
Change-Id: I2d58ac117ed1de9c3cf6e12ae38ea3a3eecabb55