ANDROID: mm: shmem: Fix kernelci build error from unused label
An ifdef guard was added around logic in shmem_get_folio_gfp to prevent
an undefined symbol when CONFIG_TRANSPARENT_HUGE_AGE=n, but that block
also contained the only reference to the label "alloced" later in the
same function. This leads to the following kernelci build failures:

With gcc-14:
mm/shmem.c: In function ‘shmem_get_folio_gfp’:
mm/shmem.c:2567:1: error: label ‘alloced’ defined but not used [-Werror=unused-label]
 2567 | alloced:
      | ^~~~~~~
  CC      arch/x86/events/intel/p4.o
  CC      crypto/kpp.o
  CC      kernel/workqueue.o
  CC      arch/x86/events/intel/p6.o
  CC      arch/x86/events/intel/pt.o
  CC      fs/inode.o
  ASN.1   crypto/rsapubkey.asn1.[ch]
  ASN.1   crypto/rsaprivkey.asn1.[ch]
  CC      crypto/rsa.o
  CC      arch/x86/events/intel/uncore.o
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:291: mm/shmem.o] Error 1
make[2]: *** [scripts/Makefile.build:548: mm] Error 2

With clang-21:
mm/shmem.c:2567:1: error: unused label 'alloced' [-Werror,-Wunused-label]
 2567 | alloced:
      | ^~~~~~~~
  AR      arch/arm/kernel/built-in.a
  CC      arch/arm/mach-orion5x/board-rd88f5182.o
  CC      arch/arm/mm/extable.o
1 error generated.
make[3]: *** [scripts/Makefile.build:291: mm/shmem.o] Error 1
make[2]: *** [scripts/Makefile.build:548: mm] Error 2

Add the same #ifdef check around the label to fix this.

Bug: 397599006
Bug: 478120558
Fixes: f7c3a55656cc ("ANDROID: mm: shmem: add vendor hooks in shmem folio allocation path")
Reported-by: kernelci.org bot <bot@kernelci.org>
Closes: https://d.kernelci.org/i/maestro:d68746ebb57c845bedf01917e257a5e7a3d5c124
Closes: https://d.kernelci.org/i/maestro:45c812656290a410c9666044020d5149cf7e106d
Change-Id: I6664ae46f264a12c526f75c72372fef59a2ee37f
Signed-off-by: Tiffany Yang <ynaffit@google.com>