kleaf: cc_testing: disable glibc fully_static_link test
This test is causing linker issues after upgrading to clang-r522817. Lets
disable it temporarily while we continue to investigate the problem.

  ld.lld: error: duplicate symbol: __lll_lock_wait_private
  ld.lld: error: duplicate symbol: __lll_unlock_wake_private

Bug: 348087663
Change-Id: I23d5dd5e6faf52c82ed002d8d0e28df3a86a9d66
Signed-off-by: Carlos Llamas <cmllamas@google.com>