net-test: fix udp checksum 0 != 0xFFFF
Perhaps scapy was updated in the mean time (as part of the
python2 to python3 transition or something) and the bug
is no longer present?

See http://b/300757486#comment9

======================================================================
FAIL: testIPv6StickyPktinfo (multinetwork_test.OutgoingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "multinetwork_base.py", line 720, in ExpectPacketOn
  File "multinetwork_base.py", line 680, in assertPacketMatches
AssertionError: "<IPv[482 chars]um=0xffff |<DNS  id=55086 qr=0 opcode=QUERY aa[165 chars]>>>>" != "<IPv[482 chars]um=0x0 |<DNS  id=55086 qr=0 opcode=QUERY aa=0 [162 chars]>>>>"
Diff is 2327 characters long. Set self.maxDiff to None to see it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multinetwork_test.py", line 307, in testIPv6StickyPktinfo
  File "multinetwork_base.py", line 722, in ExpectPacketOn
multinetwork_base.UnexpectedPacketError: IPv6 UDP using sticky pktinfo: expected UDP packet on nettest200: diff with last packet:
"<IPv[482 chars]um=0xffff |<DNS  id=55086 qr=0 opcode=QUERY aa[165 chars]>>>>" != "<IPv[482 chars]um=0x0 |<DNS  id=55086 qr=0 opcode=QUERY aa=0 [162 chars]>>>>"
Diff is 2327 characters long. Set self.maxDiff to None to see it.

Test: TreeHugger
Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Iade3cade56e31260ab4c1a716f7300dfc656398b